// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
// Live per-agent views. While workers stream, each agent gets a human-readable transcript (live/<agent>.log,
// followed by `duetto watch` and the auto-opened panes) and a status file (live/<agent>.json: what each of its
// in-flight calls is doing right now, read by watch, status and the heartbeat).

import { join } from 'node:path';
import { oneLine,                                  } from './activity.mjs';
                                              
import { appendLine, exists, fmtMs, readJson, writeJson } from './util.mjs';

                                                                                                                           
                                                                                 

export const liveDir = (runDir        ) => join(runDir, 'live');
export const liveLog = (runDir        , agent           ) => join(liveDir(runDir), `${agent}.log`);
const statusPath = (runDir        , agent           ) => join(liveDir(runDir), `${agent}.json`);

export function readLiveStatus(runDir        , agent           )             {
  const p = statusPath(runDir, agent);
  try {
    return exists(p) ? readJson            (p) : { agent, calls: {} };
  } catch {
    return { agent, calls: {} };
  }
}

const ICONS                               = { thinking: '💭', message: '💬', command: '$', file: '📄', search: '🔎', tool: '🔧', retry: '⚠', answer: '✅' };
const clock = (d = new Date()) => d.toTimeString().slice(0, 8);
/** `F1/T002/r1/implement` → `T002/r1`: enough to tell concurrent calls apart. */
const shortStep = (step        ) => step.split('/').slice(1, 3).join('/') || step;

export function formatActivity(a          , tag = '', at = new Date())         {
  const max = a.kind === 'thinking' || a.kind === 'message' ? 400 : 240;
  return `${clock(at)} ${tag ? `[${tag}] ` : ''}${ICONS[a.kind]} ${oneLine(a.text, max)}`;
}

/** Track one worker call in its agent's live files. */
export function liveCall(runDir        , agent           , o                                               ) {
  const log = liveLog(runDir, agent);
  const now = new Date().toISOString();
  const update = (fn                         ) => {
    const s = readLiveStatus(runDir, agent);
    fn(s);
    writeJson(statusPath(runDir, agent), s);
  };
  const call             = { step: o.step, role: o.role, started_at: now, last_at: now, last: 'starting…', events: 0 };
  update((s) => (s.calls[o.label] = call));
  appendLine(log, `\n── ${o.step} · ${o.role} · started ${clock()} ──`);
  return {
    onActivity(a          ) {
      call.events++;
      call.last = `${ICONS[a.kind]} ${oneLine(a.text, 120)}`;
      call.last_at = new Date().toISOString();
      // Several calls of the same agent can run at once (parallel task waves): tag their lines.
      const concurrent = Object.keys(readLiveStatus(runDir, agent).calls).length > 1;
      appendLine(log, formatActivity(a, concurrent ? shortStep(o.step) : ''));
      update((s) => (s.calls[o.label] = call));
    },
    end(outcome                                                               ) {
      const cost = outcome.costUsd ? `, $${outcome.costUsd.toFixed(2)}` : '';
      appendLine(log, `── ${o.step} ${outcome.ok ? '✓ done' : `✖ failed: ${oneLine(outcome.error ?? '', 160)}`} (${fmtMs(outcome.ms)}${cost}) ──`);
      update((s) => delete s.calls[o.label]);
    },
  };
}
