// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
// The workflow, expressed as a generator of steps. Every step's completion is derived from artifacts
// on disk, so the "current position" is always recomputed: resuming after a crash is just running again.

import { existsSync, mkdirSync, readdirSync, renameSync, rmSync } from 'node:fs';
import { basename, join } from 'node:path';
import { other, runAgent,             } from './agents/index.mjs';
                                              
import { bounceConflicts } from './conflict.mjs';
import { runChecks,                  } from './checks.mjs';
                                          
import { addWorktree, commitAll, diff, git, head, removeWorktree, restore, snapshot, worktreePath } from './git.mjs';
import { liveCall } from './live.mjs';
import { hostInstructions, workerPrompt } from './prompt.mjs';
import * as render from './render.mjs';
import { SCHEMAS,                                                                    } from './schemas.mjs';
import { logEvent,               } from './state.mjs';
import { appendLine, exec, exists, fmtMs, readJson, readText, sh, sha, slugify, tail, topoSort, writeJson, writeText } from './util.mjs';
import { highestReserved, registerFeature } from './features.mjs';
import { detect, nextFeatureNumber, resolveTemplate, writeFeatureDir } from './speckit.mjs';
import { planWaves } from './waves.mjs';

                   
               
              
                 
                  
                 
                                
  

                        
                       
                                 
                 
                 
                                                                           
                                   
                                              
  

                    
                    
                       
                 
                                                      
  

/** Spec Kit's phases, in pipeline order; `duetto <phase>` runs a feature up to the end of one. */
export const PHASES = ['scan', 'decompose', 'specify', 'clarify', 'plan', 'tasks', 'analyze', 'implement', 'converge']         ;
                                            

                    
             
                
                                                     
                                                          
                
                   
                      
                            
                  
              
  


// ───────────────────────────── step helpers ─────────────────────────────

const label = (id        ) => id.replace(/[^\w.-]+/g, '__');

async function callAgent(
  ctx     ,
  agent           ,
  o                                                                                                ,
)               {
  ctx.print(`    ${agent} ▸ ${o.role} (${o.stepId})…`);
  const live = liveCall(ctx.dir, agent, { label: `${label(o.stepId)}.${agent}`, step: o.stepId, role: o.role });
  const started = Date.now();
  const res = await runAgent(ctx.agents[agent], {
    role: o.role,
    prompt: o.prompt,
    cwd: o.cwd,
    writable: o.writable,
    schema: SCHEMAS[o.schema],
    rawDir: join(ctx.dir, 'raw'),
    label: `${label(o.stepId)}.${agent}`,
    timeoutMs: ctx.config.timeout_minutes * 60_000,
    onActivity: live.onActivity,
  }).catch((err) => {
    live.end({ ok: false, ms: Date.now() - started, error: (err         ).message });
    throw err;
  });
  live.end({ ok: true, ms: res.durationMs, costUsd: res.costUsd });
  logEvent(ctx.dir, { type: 'agent', step: o.stepId, agent, role: o.role, duration_ms: res.durationMs, cost_usd: res.costUsd, attempts: res.attempts });
  ctx.print(`    ${agent} ✓ ${o.role} (${o.stepId}, ${fmtMs(res.durationMs)}${res.costUsd ? `, $${res.costUsd.toFixed(2)}` : ''})`);
  return res.output;
}

/** The same prompt-shaped job for both models, in parallel; only missing outputs are (re)run. */
function both(
  ctx     ,
  o                                                                                                                                         ,
)       {
  return {
    id: o.id,
    title: o.title,
    kind: 'worker',
    done: () => exists(o.out('claude')) && exists(o.out('codex')),
    run: async () => {
      const todo = (['claude', 'codex']         ).filter((a) => !exists(o.out(a)));
      const results = await Promise.allSettled(
        todo.map(async (a) => {
          const output = await callAgent(ctx, a, { stepId: o.id, role: o.role, prompt: o.prompt(a), cwd: o.cwd, writable: false, schema: o.schema });
          writeJson(o.out(a), output);
        }),
      );
      const failed = results.filter((r) => r.status === 'rejected')                           ;
      if (failed.length) throw new Error(failed.map((f) => (f.reason         ).message).join('\n'));
    },
  };
}

function host(id        , title        , task          )       {
  return { id, title, kind: 'host', done: () => exists(task.output), host: task };
}

function gate(id        , title        , g      )       {
  return { id, title, kind: 'user', done: () => exists(g.output), gate: g };
}

function det(id        , title        , marker        , run                        )       {
  return {
    id,
    title,
    kind: 'deterministic',
    done: () => exists(marker),
    run: async () => {
      const result = await run();
      writeJson(marker, result ?? { ok: true });
    },
  };
}

const option = (key        , label        , description        ) => ({ key, label, description });

function singleQuestion(id        , text        , options                             , suggested               )          {
  return { id, text, category: 'other', blocking: true, affects: [], options, claude: null, codex: null, status: 'single', suggested };
}

const choiceOf = (path        , qid        )         => (readJson(path).answers            ).find((a) => a.id === qid)?.choice ?? '';

// ───────────────────────────── pipeline ─────────────────────────────

/** The phase a step belongs to, from its id. One table, so a new step can't silently fall outside every phase. */
export function phaseOf(id        )                                     {
  if (id === 'scan') return { phase: 'scan' };
  if (id.startsWith('decompose')) return { phase: 'decompose' };
  const [feature, rest = ''] = [id.slice(0, id.indexOf('/')), id.slice(id.indexOf('/') + 1)];
  const table                    = [
    [/^spec-reconcile/, 'plan'],
    [/^(plan|tasks)-reconcile/, 'tasks'],
    [/^(setup|templates|research|specify$)/, 'specify'],
    [/^(clarify-|specify-revise)/, 'clarify'],
    [/^(plan|challenge)/, 'plan'],
    [/^(tasks|spec-commit|waves)$/, 'tasks'],
    [/^analyze/, 'analyze'],
    [/^(T\d+|W\d+\/)/, 'implement'],
    [/^(converge-|FIX\d+|report$)/, 'converge'],
  ];
  const hit = /^F\d+$/.test(feature) ? table.find(([re]) => re.test(rest)) : undefined;
  if (!hit) throw new Error(`No phase for step ${id}`);
  return { phase: hit[1], feature };
}

export function* pipeline(ctx     )                  {
  for (const step of steps(ctx)) yield Object.assign(step, phaseOf(step.id));
}

function* steps(ctx     )                  {
  const D = ctx.dir;
  const request = join(D, 'request.md');

  yield both(ctx, {
    id: 'scan',
    title: 'Codebase scan (Claude ∥ Codex)',
    role: 'scanner',
    schema: 'Scan',
    cwd: ctx.repo,
    out: (a) => join(D, `scan.${a}.json`),
    prompt: () => workerPrompt('scanner', ctx.repo, { request: readText(request) }),
  });

  if (ctx.state.mode === 'single') yield singleFeature(ctx);
  else yield* decompose(ctx);

  const features = topoSort(readJson                         (join(D, 'decomposition.json')).features);
  let prev                 = null;
  for (const f of features) {
    yield* feature(ctx, f, prev);
    prev = f;
  }
}

/** `# Feature Specification: Title` → `Title`. */
export const specTitle = (md        ) => md.match(/^#\s+(?:Feature Specification:\s*)?(.+)$/m)?.[1].trim() ?? null;

/** `duetto specify`: the request is one feature, so decomposition is just bookkeeping. */
function singleFeature(ctx     )       {
  const out = join(ctx.dir, 'decomposition.json');
  return {
    id: 'decompose',
    title: 'Single feature',
    kind: 'deterministic',
    done: () => exists(out),
    run: async () => {
      const request = readText(join(ctx.dir, 'request.md')).trim();
      const adopted = ctx.state.adopted?.spec_dir;
      const title = adopted ? specTitle(readText(join(ctx.dir, 'adopted-spec.md'))) ?? request : request.split('\n')[0].slice(0, 80);
      const slug = adopted ? basename(adopted).replace(/^\d+-/, '') : slugify(request, 40);
      const rationale = adopted ? `Adopted ${adopted} (written with Spec Kit).` : 'Single feature (duetto specify).';
      const d = { rationale, features: [{ id: 'F1', slug, title, summary: request, scope: request, depends_on: [] }] };
      writeJson(out, d);
      writeText(join(ctx.dir, 'decomposition.md'), render.renderDecomposition(d));
    },
  };
}

function* decompose(ctx     )                  {
  const D = ctx.dir;
  const out = join(D, 'decomposition.json');
  const feedback = join(D, 'decompose-feedback.md');
  yield host('decompose', 'Decompose request into features', {
    instructions: hostInstructions('decompose'),
    inputs: {
      request: join(D, 'request.md'),
      scan_claude: join(D, 'scan.claude.json'),
      scan_codex: join(D, 'scan.codex.json'),
      ...(exists(feedback) ? { user_feedback_on_previous_split: feedback } : {}),
    },
    schema: 'Decomposition',
    output: out,
    postprocess: (d) => {
      if (!d.features.length) throw new Error('At least one feature is required');
      const ids = new Set        ();
      for (const f of d.features) {
        if (ids.has(f.id)) throw new Error(`Duplicate feature id ${f.id}`);
        ids.add(f.id);
        if (!/^[a-z0-9-]+$/.test(f.slug)) throw new Error(`Slug "${f.slug}" must be kebab-case`);
      }
      topoSort(d.features);
      return d;
    },
    after: (d) => writeText(join(D, 'decomposition.md'), render.renderDecomposition(d)),
  });

  const approval = join(D, 'decomposition.approval.json');
  yield gate('decompose-approve', 'Approve feature split', {
    context: [join(D, 'decomposition.md')],
    questions: [
      singleQuestion(
        'SPLIT',
        'Approve this feature split? (see decomposition.md) — or answer with free-text feedback to redo it',
        [option('approve', 'Approve', 'Proceed feature by feature in dependency order')],
        'approve',
      ),
    ],
    output: approval,
    after: (answers) => {
      const a = answers[0];
      if (a.choice === 'approve') return;
      const n = readdirSync(D).filter((f) => f.startsWith('decomposition.rejected')).length + 1;
      renameSync(out, join(D, `decomposition.rejected-${n}.json`));
      appendLine(feedback, `- Split #${n} rejected: ${a.choice}`);
      rmSync(approval);
    },
  });
}

                                                                                                                                                

/** Renders a feature's Spec Kit documents into its specs/NNN-slug/ dir. */
/** Checkbox state is progress, not an edit. */
const normalizeMd = (md        ) => md.replace(/^(\s*- )\[[xX]\]/gm, '$1[ ]').trim();
const renderedPath = (FD        ) => join(FD, 'rendered.json');

/** True when the user edited a rendered document (spec.md, plan.md, tasks.md) since duetto last wrote it. */
function drifted(FD        , meta             , doc        )          {
  const file = join(meta.specDir, doc);
  const recorded = exists(renderedPath(FD)) ? readJson(renderedPath(FD))[doc] : undefined;
  return Boolean(recorded && exists(file) && sha(normalizeMd(readText(file))) !== recorded);
}

function docs(ctx     , FD        , meta             ) {
  const w = (n        , c        ) => {
    writeText(join(meta.specDir, n), c);
    if (['spec.md', 'plan.md', 'tasks.md'].includes(n)) writeJson(renderedPath(FD), { ...(exists(renderedPath(FD)) ? readJson(renderedPath(FD)) : {}), [n]: sha(normalizeMd(c)) });
  };
  const finalSpec = join(FD, 'spec-final.json');
  const specFile = () => (exists(finalSpec) ? finalSpec : join(FD, 'spec.json'));
  const docMeta = () => ({ branch: meta.branch, request: readText(join(ctx.dir, 'request.md')), date: ctx.state.created_at.slice(0, 10) });
  return {
    spec: (d = readJson(specFile())) => w('spec.md', render.renderSpec(d, { ...docMeta(), status: exists(finalSpec) ? 'Clarified' : 'Draft' })),
    plan: (plan     , extra                                          ) => {
      const title = readJson(specFile()).title;
      w('plan.md', render.renderPlan(plan, extra, { ...docMeta(), title }));
      for (const [name, content] of Object.entries(render.planFiles(plan, title))) w(name, content);
    },
    tasks: (assignments                        , alsoDone           = []) => {
      const tasksDir = join(FD, 'tasks');
      const done = new Set([...(existsSync(tasksDir) ? readdirSync(tasksDir).filter((t) => exists(join(tasksDir, t, 'commit.json'))) : []), ...alsoDone]);
      const waves = exists(join(FD, 'waves.json')) ? readJson(join(FD, 'waves.json')).waves : undefined;
      const specDir = meta.specDir.startsWith(meta.worktree + '/') ? meta.specDir.slice(meta.worktree.length + 1) : meta.specDir;
      w('tasks.md', render.renderTasks(readJson(join(FD, 'tasks.json')), { assignments, spec: readJson(specFile()), waves, done, specDir }));
    },
  };
}

function* feature(ctx     , f         , prev                )                  {
  const FD = join(ctx.dir, 'features', f.id);
  const p = (name        ) => join(FD, name);
  const depth = ctx.state.depth;
  const quick = depth === 'quick';

  // ── setup: stacked worktree/branch, spec number, dependency install
  const inplace = ctx.config.workspace === 'inplace' && ctx.state.mode === 'single';
  yield det(`${f.id}/setup`, inplace ? `${f.id}: create feature branch` : `${f.id}: create worktree`, p('feature.json'), async () => {
    const base = prev ? (readJson             (join(ctx.dir, 'features', prev.id, 'feature.json')).branch) : ctx.state.base_commit;
    const baseSha = await git(ctx.repo, 'rev-parse', base);
    const adopted = ctx.state.adopted?.spec_dir;
    const numberIn = (specsRoot        ) =>
      adopted ? (basename(adopted).match(/^(\d+)-/)?.[1] ?? '000') : String(Math.max(Number(nextFeatureNumber(specsRoot)), highestReserved(ctx.repo) + 1)).padStart(3, '0');
    let wt        , branch        , number        ;
    if (inplace) {
      // Spec Kit's own flow: a NNN-slug branch in the user's checkout (like its git extension).
      const dirty = (await git(ctx.repo, 'status', '--porcelain')).split('\n').filter((l) => l && !/\.duetto\/|\.gitignore$|\.specify\/feature\.json$/.test(l));
      if (dirty.length) throw new Error(`workspace "inplace" works in your checkout and needs it clean; commit or stash first:\n${dirty.slice(0, 8).join('\n')}`);
      wt = ctx.repo;
      number = numberIn(join(wt, 'specs'));
      branch = `${number}-${f.slug}`;
      const exists_ = (await exec('git', ['rev-parse', '--verify', '--quiet', `refs/heads/${branch}`], { cwd: ctx.repo })).code === 0;
      await git(ctx.repo, 'checkout', ...(exists_ ? [branch] : ['-b', branch, baseSha]));
    } else {
      wt = worktreePath(ctx.repo, ctx.config.worktrees_dir, ctx.state.id, f.id);
      branch = `duetto/${ctx.state.id}/${f.id}-${f.slug}`;
      if (!existsSync(wt)) await addWorktree(ctx.repo, wt, branch, baseSha);
      number = numberIn(join(wt, 'specs'));
    }
    await runSetup(ctx, wt);
    const specDir = adopted ?? `specs/${number}-${f.slug}`;
    const meta              = { id: f.id, title: f.title, slug: f.slug, number, branch, worktree: wt, base: baseSha, specDir: join(wt, specDir) };
    registerFeature(ctx.repo, { run: ctx.state.id, feature: f.id, spec_dir: specDir, branch, worktree: wt });
    writeFeatureDir(wt, specDir); // Spec Kit's commands, run inside the worktree, find this feature
    return meta;
  });
  const meta = readJson             (p('feature.json'));
  const wt = meta.worktree;
  const md = (name        , content        ) => writeText(join(meta.specDir, name), content);
  const doc = docs(ctx, FD, meta);

  // ── the project's Spec Kit templates (or bundled copies), as structure guides for the host
  yield det(`${f.id}/templates`, `${f.id}: resolve Spec Kit templates`, p('templates/resolved.json'), async () => {
    for (const name of ['spec-template', 'plan-template', 'tasks-template']         ) writeText(p(`templates/${name}.md`), await resolveTemplate(ctx.repo, name));
    return { speckit: detect(ctx.repo) };
  });
  const ctxInputs = () => ({ request: readText(join(ctx.dir, 'request.md')), feature: f, codebase_scans: { claude: readJson(join(ctx.dir, 'scan.claude.json')), codex: readJson(join(ctx.dir, 'scan.codex.json')) } });

  // ── research: independent → rebuttal → host synthesis
  yield both(ctx, {
    id: `${f.id}/research`,
    title: `${f.id}: research (Claude ∥ Codex)`,
    role: 'researcher',
    schema: 'Research',
    cwd: wt,
    out: (a) => p(`research.${a}.json`),
    prompt: () => workerPrompt('researcher', ctx.repo, ctxInputs()),
  });
  if (!quick) {
    yield both(ctx, {
      id: `${f.id}/research-rebuttal`,
      title: `${f.id}: research rebuttal`,
      role: 'rebutter',
      schema: 'Rebuttal',
      cwd: wt,
      out: (a) => p(`research-rebuttal.${a}.json`),
      prompt: (a) => workerPrompt('rebutter', ctx.repo, { feature: f, your_output: readJson(p(`research.${a}.json`)), their_output: readJson(p(`research.${other(a)}.json`)) }),
    });
  }
  yield host(`${f.id}/research-synthesis`, `${f.id}: synthesize research`, {
    instructions: hostInstructions('research'),
    inputs: pick({
      feature_decomposition: join(ctx.dir, 'decomposition.json'),
      research_claude: p('research.claude.json'),
      research_codex: p('research.codex.json'),
      rebuttal_claude: quick ? null : p('research-rebuttal.claude.json'),
      rebuttal_codex: quick ? null : p('research-rebuttal.codex.json'),
    }),
    schema: 'ResearchSynthesis',
    output: p('research.json'),
    after: (d) => md('research.md', render.renderResearch(d)),
  });

  // ── spec draft first, then clarify against it (Spec Kit's order: specify → clarify)
  const adopted = ctx.state.adopted ? join(ctx.dir, 'adopted-spec.md') : null;
  yield host(`${f.id}/specify`, adopted ? `${f.id}: import your Spec Kit spec` : `${f.id}: write spec`, {
    instructions: hostInstructions(adopted ? 'specify-import' : 'specify'),
    inputs: adopted
      ? { spec_md: adopted, research: p('research.json'), spec_template: p('templates/spec-template.md') }
      : { request: join(ctx.dir, 'request.md'), decomposition: join(ctx.dir, 'decomposition.json'), research: p('research.json'), spec_template: p('templates/spec-template.md') },
    schema: 'Spec',
    output: p('spec.json'),
    after: (d) => doc.spec(d),
  });

  // ── clarification rounds against the draft
  const maxRounds = ctx.config.max_clarify_rounds[depth];
  const answered                                                               = [];
  for (let r = 1; r <= maxRounds; r++) {
    const prior = [...answered];
    yield both(ctx, {
      id: `${f.id}/clarify-${r}`,
      title: `${f.id}: clarifying questions, round ${r}`,
      role: 'questioner',
      schema: 'Questions',
      cwd: wt,
      out: (a) => p(`clarify-${r}.${a}.json`),
      prompt: () => workerPrompt('questioner', ctx.repo, { ...ctxInputs(), research: readJson(p('research.json')), spec_draft: readJson(p('spec.json')), previous_answers: prior }),
    });
    yield host(`${f.id}/clarify-${r}-merge`, `${f.id}: merge questions, round ${r}`, {
      instructions: hostInstructions('clarify'),
      inputs: { questions_claude: p(`clarify-${r}.claude.json`), questions_codex: p(`clarify-${r}.codex.json`), spec_draft: p('spec.json'), research: p('research.json'), ...answerInputs(FD, r) },
      schema: 'MergedQuestions',
      output: p(`questions-${r}.json`),
      postprocess: (d) => normalizeQuestions(d),
    });
    const qs = readJson                          (p(`questions-${r}.json`)).questions;
    if (!qs.length) break;
    yield gate(`${f.id}/clarify-${r}-answers`, `${f.id}: answer clarifying questions (round ${r})`, {
      context: [join(meta.specDir, 'spec.md'), join(meta.specDir, 'research.md')],
      questions: qs,
      output: p(`answers-${r}.json`),
      after: () => renderDecisionsMd(FD, meta),
    });
    answered.push({ round: r, questions: qs, answers: readJson(p(`answers-${r}.json`)).answers });
  }


  // ── spec revision with the user's answers. Runs made before this order existed (plan already started) skip it.
  const specFinal = p('spec-final.json');
  if (answered.length && (exists(specFinal) || !exists(p('plan.claude.json')))) {
    yield host(`${f.id}/specify-revise`, `${f.id}: revise spec with your answers`, {
      instructions: hostInstructions('specify-revise'),
      inputs: { spec_draft: p('spec.json'), spec_template: p('templates/spec-template.md'), ...answerInputs(FD) },
      schema: 'Spec',
      output: specFinal,
      after: (d) => doc.spec(d),
    });
  }
  const specPath = exists(specFinal) ? specFinal : p('spec.json');
  const planInputs = () => ({ feature: f, spec: readJson(specPath), research: readJson(p('research.json')), decisions: allAnswers(FD) });

  yield* reconcile(ctx, FD, meta, { doc: 'spec.md', json: specPath, schema: 'Spec', render: (d) => doc.spec(d), downstream: [...PLAN_FILES, ...TASK_FILES] });

  // ── plan: independent → rebuttal → host synthesis (+ escalated decisions)
  yield both(ctx, {
    id: `${f.id}/plan`,
    title: `${f.id}: plan (Claude ∥ Codex)`,
    role: 'planner',
    schema: 'Plan',
    cwd: wt,
    out: (a) => p(`plan.${a}.json`),
    prompt: () => workerPrompt('planner', ctx.repo, planInputs()),
  });
  if (!quick) {
    yield both(ctx, {
      id: `${f.id}/plan-rebuttal`,
      title: `${f.id}: plan rebuttal`,
      role: 'rebutter',
      schema: 'Rebuttal',
      cwd: wt,
      out: (a) => p(`plan-rebuttal.${a}.json`),
      prompt: (a) => workerPrompt('rebutter', ctx.repo, { spec: readJson(specPath), your_output: readJson(p(`plan.${a}.json`)), their_output: readJson(p(`plan.${other(a)}.json`)) }),
    });
  }
  yield* decided(ctx, FD, meta, {
    id: `${f.id}/plan-synthesis`,
    title: `${f.id}: synthesize plan`,
    instructions: hostInstructions('plan'),
    inputs: pick({
      spec: specPath,
      plan_claude: p('plan.claude.json'),
      plan_codex: p('plan.codex.json'),
      rebuttal_claude: quick ? null : p('plan-rebuttal.claude.json'),
      rebuttal_codex: quick ? null : p('plan-rebuttal.codex.json'),
      plan_template: p('templates/plan-template.md'),
      ...answerInputs(FD),
    }),
    schema: 'PlanSynthesis',
    synth: p('plan-synthesis.json'),
    final: p('plan.json'),
    answers: p('plan-decisions.json'),
  });

  // ── challenge: both attack the plan → host folds in
  let finalPlan = p('plan.json');
  if (!quick) {
    yield both(ctx, {
      id: `${f.id}/challenge`,
      title: `${f.id}: challenge the plan (Claude ∥ Codex)`,
      role: 'challenger',
      schema: 'Challenge',
      cwd: wt,
      out: (a) => p(`challenge.${a}.json`),
      prompt: () => workerPrompt('challenger', ctx.repo, { spec: readJson(specPath), plan: readJson(p('plan.json')).plan, decisions: allAnswers(FD) }),
    });
    yield* decided(ctx, FD, meta, {
      id: `${f.id}/challenge-synthesis`,
      title: `${f.id}: fold in challenge findings`,
      instructions: hostInstructions('challenge'),
      inputs: { spec: specPath, plan: p('plan.json'), challenge_claude: p('challenge.claude.json'), challenge_codex: p('challenge.codex.json') },
      schema: 'ChallengeSynthesis',
      synth: p('challenge-synthesis.json'),
      final: p('plan-final.json'),
      answers: p('challenge-decisions.json'),
    });
    finalPlan = p('plan-final.json');
  }
  const plan = () => readJson(finalPlan).plan;
  yield* reconcile(ctx, FD, meta, { doc: 'plan.md', json: finalPlan, schema: 'PlanFinal', render: (d) => doc.plan(d.plan), downstream: TASK_FILES });

  // ── tasks DAG
  yield host(`${f.id}/tasks`, `${f.id}: break plan into tasks`, {
    instructions: hostInstructions('tasks'),
    inputs: { spec: specPath, plan: finalPlan, tasks_template: p('templates/tasks-template.md') },
    schema: 'Tasks',
    output: p('tasks.json'),
    postprocess: validateTasks,
  });
  const assign = (ts        ) => Object.fromEntries(topoSort(ts).map((t, i) => [t.id, i % 2 === 0 ? ctx.config.first_implementer : other(ctx.config.first_implementer)]))                             ;
  yield* reconcile(ctx, FD, meta, { doc: 'tasks.md', json: p('tasks.json'), schema: 'Tasks', postprocess: validateTasks, render: (d) => doc.tasks(assign(d.tasks)), downstream: ['waves.json', 'spec-commit.json', ...ANALYSIS_FILES] });
  const tasks = topoSort(readJson                   (p('tasks.json')).tasks);
  const assignment = assign(tasks);

  // ── waves: independent tasks run concurrently (scheduled before the spec commit so tasks.md can mark [P]).
  // Already-started tasks (a run resumed after upgrading) stay solo in the feature worktree they began in.
  yield det(`${f.id}/waves`, `${f.id}: schedule tasks`, p('waves.json'), async () => ({
    waves: planWaves(tasks, ctx.config.parallel_tasks, (t) => exists(join(FD, 'tasks', t.id, 'base.json'))).map((w) => w.map((t) => t.id)),
  }));
  yield det(`${f.id}/spec-commit`, `${f.id}: commit spec artifacts`, p('spec-commit.json'), async () => {
    renderAll(ctx, FD, meta, finalPlan, assignment);
    const sha = await commitAll(wt, `docs(${meta.number}): spec, plan and tasks for ${f.title}\n\nGenerated by duetto run ${ctx.state.id}.`);
    return { sha };
  });

  // ── analyze (Spec Kit's /analyze, both models): on request (`duetto analyze`), or at deep depth for runs that
  // hadn't started implementing when this phase was introduced
  const autoAnalyze = depth === 'deep' && (exists(p('analysis.json')) || !existsSync(join(FD, 'tasks')));
  if (autoAnalyze || exists(p('analyze.requested'))) {
    const docsInput = () => ({ spec: readJson(specPath), plan: plan(), tasks: readJson(p('tasks.json')).tasks });
    yield both(ctx, {
      id: `${f.id}/analyze`,
      title: `${f.id}: analyze spec, plan and tasks (Claude ∥ Codex)`,
      role: 'analyzer',
      schema: 'Analysis',
      cwd: wt,
      out: (a) => p(`analysis.${a}.json`),
      prompt: () => workerPrompt('analyzer', ctx.repo, docsInput()),
    });
    yield host(`${f.id}/analyze-synthesis`, `${f.id}: merge the analyses`, {
      instructions: hostInstructions('analyze'),
      inputs: { analysis_claude: p('analysis.claude.json'), analysis_codex: p('analysis.codex.json'), spec: specPath, plan: finalPlan, tasks: p('tasks.json') },
      schema: 'AnalysisSynthesis',
      output: p('analysis.json'),
      after: (d) => {
        md('analysis.md', render.renderAnalysis(d));
        const serious = d.findings.filter((x     ) => x.severity === 'critical' || x.severity === 'high');
        if (serious.length) ctx.print(`    analysis: ${serious.length} critical/high finding(s) — see analysis.md; implementers will be told about them`);
      },
    });
  }

  // ── implement: alternate implementer/reviewer per task
  const waves = readJson                       (p('waves.json')).waves.map((ids) => ids.map((id) => tasks.find((t) => t.id === id) ));
  const shared = { ctx, FD, meta, spec: () => readJson(specPath), plan, tasks, assignment };
  for (const [i, wave] of waves.entries()) {
    if (wave.length === 1) yield* taskLoop(shared, wave[0], assignment[wave[0].id]);
    else yield* parallelWave(shared, `W${i + 1}`, wave, assignment);
  }

  // ── converge: whole-feature audit by the model that implemented less
  const counts = { claude: 0, codex: 0 };
  for (const t of tasks) counts[assignment[t.id]]++;
  const auditor            = counts.claude <= counts.codex ? 'claude' : 'codex';
  for (let c = 1; ; c++) {
    const checksPath = p(`final-checks-${c}.json`);
    const out = p(`converge-${c}.json`);
    yield {
      id: `${f.id}/converge-${c}`,
      title: `${f.id}: convergence audit by ${auditor}`,
      kind: 'worker',
      done: () => exists(out),
      run: async () => {
        const checks = exists(checksPath) ? readJson(checksPath) : await runChecks(ctx.config, wt, meta.base, null);
        writeJson(checksPath, checks);
        const { stat, patch } = await diff(wt, meta.base);
        const result = await callAgent(ctx, auditor, {
          stepId: `${f.id}/converge-${c}`,
          role: 'converger',
          writable: false,
          cwd: wt,
          schema: 'Converge',
          prompt: workerPrompt('converger', ctx.repo, { spec: shared.spec(), plan: plan(), tasks, checks: checksForPrompt(checks), diff_stat: stat, diff: patch }),
        });
        writeJson(out, result);
      },
    };
    const conv = readJson(out);
    if (conv.status === 'converged') break;
    const decision = p(`converge-${c}-decision.json`);
    yield gate(`${f.id}/converge-${c}-decision`, `${f.id}: convergence found issues`, {
      context: [out],
      questions: [
        singleQuestion(
          'CONVERGE',
          `${auditor} found unmet criteria / open findings: ${conv.summary}`,
          [
            option('fix', 'Fix', `${other(auditor)} implements a fix task, ${auditor} reviews it`),
            option('accept', 'Accept as-is', 'Ship with the findings recorded in the report'),
            option('abort', 'Abort run', 'Stop here'),
          ],
          'fix',
        ),
      ],
      output: decision,
    });
    const choice = choiceOf(decision, 'CONVERGE');
    if (choice === 'accept') break;
    if (choice === 'abort') {
      yield aborted(`${f.id}/converge-${c}`);
      return;
    }
    const fixTask       = {
      id: `FIX${c}`,
      title: 'Address convergence findings',
      description: `Fix the convergence audit findings below.${choice !== 'fix' ? `\nUser guidance: ${choice}` : ''}\n\n${JSON.stringify({ unmet: conv.acceptance.filter((a     ) => !a.met), findings: conv.findings }, null, 2)}`,
      depends_on: [],
      files_in_scope: [],
      acceptance: [...conv.acceptance.filter((a     ) => !a.met).map((a     ) => `${a.id} is met`), ...conv.findings.map((x     ) => x.required_change)],
      test_command: null,
    };
    yield* taskLoop(shared, fixTask, other(auditor));
  }

  yield det(`${f.id}/report`, `${f.id}: write report`, p('report.json'), async () => {
    const all = [...tasks.map((t) => t.id), ...readdirSync(join(FD, 'tasks')).filter((n) => n.startsWith('FIX') || n.endsWith('-rerun'))];
    const rows = all.map((id) => {
      const c = readJson(join(FD, 'tasks', id, 'commit.json'));
      const title = tasks.find((t) => t.id === id.replace(/-rerun$/, ''))?.title ?? 'Convergence fixes';
      return { id, title, ...c, ...mergedSha(FD, id) };
    });
    const lastConv = lastNumbered(FD, 'converge-', '.json', (n) => !n.includes('decision'));
    const lastChecks = lastNumbered(FD, 'final-checks-', '.json');
    renderAll(ctx, FD, meta, finalPlan, assignment);
    md('report.md', render.renderReport({ feature: f, tasks: rows, converge: lastConv ? readJson(lastConv) : { status: '?', summary: '', acceptance: [], findings: [] }, checks: lastChecks ? readJson(lastChecks) : null }));
    const sha = await commitAll(wt, `docs(${meta.number}): duetto report for ${f.title}`);
    return { sha, branch: meta.branch, worktree: wt };
  });
}

// ───────────────────────────── task loop ─────────────────────────────

                                                                                                                                                  

function* taskLoop(s        , t      , impl           , wt = s.meta.worktree)                  {
  const { ctx, meta } = s;
  const rev = other(impl);
  const TD = join(s.FD, 'tasks', t.id);
  const p = (n        ) => join(TD, n);
  const id = `${meta.id}/${t.id}`;

  yield det(`${id}/start`, `${id}: start task`, p('base.json'), async () => ({ base: await head(wt), implementer: impl, reviewer: rev, task: t }));
  const base = readJson(p('base.json')).base          ;

  let limit = ctx.config.max_review_rounds;
  let escalations = 0;
  let accepted = false;
  for (let r = 1; ; r++) {
    const prevReview = r > 1 ? readJson(p(`review-${r - 1}.json`)) : null;
    const prevChecks = r > 1 ? readJson(p(`checks-${r - 1}.json`)) : null;
    // A polish round follows an approved, passing round: its fixes are gated by checks, not re-reviewed.
    const polishing = prevReview?.status === 'approved' && Boolean(prevChecks?.passed);
    const guidance = escalationGuidance(TD, escalations);

    yield {
      id: `${id}/r${r}/implement`,
      title: `${id}: ${impl} implements (round ${r})`,
      kind: 'worker',
      done: () => exists(p(`impl-${r}.json`)),
      run: async () => {
        if (polishing) ctx.print(`    polish: ${rev} approved with ${ctx.config.review.polish.join('/')} findings — one polish round`);
        const out = await callAgent(ctx, impl, {
          stepId: `${id}/r${r}/implement`,
          role: 'implementer',
          writable: true,
          cwd: wt,
          schema: 'Implementation',
          prompt: workerPrompt(
            'implementer',
            ctx.repo,
            {
              spec: s.spec(),
              plan: s.plan(),
              task: t,
              all_tasks: s.tasks.map((x) => ({ id: x.id, title: x.title, depends_on: x.depends_on })),
              review_findings_to_address: prevReview,
              polish_round: polishing
                ? `${rev} approved your work but raised minor findings. Address each one, or dispute it with reasoning; make no unrelated changes. There is no further review: the project's checks must still pass.`
                : null,
              failing_checks: prevChecks && !prevChecks.passed ? summarizeChecks(prevChecks) : null,
              user_guidance: guidance.length ? guidance : null,
              analysis_findings: seriousAnalysis(s.FD),
            },
            `You are ${impl}. Round ${r}. ${rev} will review your work.`,
          ),
        });
        writeJson(p(`impl-${r}.json`), out);
      },
    };

    yield det(`${id}/r${r}/checks`, `${id}: run checks (round ${r})`, p(`checks-${r}.json`), async () => {
      const res = await runChecks(ctx.config, wt, base, t);
      ctx.print(`    checks: ${res.passed ? 'passed' : 'FAILED'} (${res.commands.map((c) => `${c.cmd}=${c.exit_code}`).join(', ') || 'no commands configured'})`);
      return res;
    });
    if (polishing && readJson             (p(`checks-${r}.json`)).passed) break;

    yield {
      id: `${id}/r${r}/review`,
      title: `${id}: ${rev} reviews (round ${r})`,
      kind: 'worker',
      done: () => exists(p(`review-${r}.json`)),
      run: async () => {
        const before = await snapshot(wt);
        const { stat, patch } = await diff(wt, base);
        const out = await callAgent(ctx, rev, {
          stepId: `${id}/r${r}/review`,
          role: 'reviewer',
          writable: false,
          cwd: wt,
          schema: 'Review',
          prompt: workerPrompt(
            'reviewer',
            ctx.repo,
            {
              spec: s.spec(),
              plan: s.plan(),
              task: t,
              implementation_report: readJson(p(`impl-${r}.json`)),
              checks: checksForPrompt(readJson(p(`checks-${r}.json`))),
              previous_review: prevReview,
              diff_stat: stat,
              diff: patch,
            },
            `You are ${rev}, reviewing ${impl}'s work. Round ${r} of at most ${limit}. Base commit: ${base}.`,
          ),
        });
        const after = await snapshot(wt);
        if (after !== before) {
          await restore(wt, before);
          throw new Error(`Reviewer ${rev} modified the worktree during review; changes were reverted and the review discarded. Run again to retry.`);
        }
        const blocking = out.findings.filter((x     ) => ctx.config.review.blocking.includes(x.severity));
        if (out.status === 'approved' && blocking.length) out.status = 'changes_required';
        writeJson(p(`review-${r}.json`), out);
        ctx.print(`    review: ${out.status} (${out.findings.length} findings, ${blocking.length} blocking)`);
      },
    };

    const review = readJson(p(`review-${r}.json`));
    const checks = readJson             (p(`checks-${r}.json`));
    if (review.status === 'approved' && checks.passed) {
      // Polish: an approved review with low-severity findings gets one more implement/review round,
      // so findings both models agree are worth fixing don't silently ship.
      const polishUsed = countPolishRounds(TD, r - 1, ctx.config.review.polish);
      if (!hasPolishFindings(review, ctx.config.review.polish) || polishUsed >= ctx.config.review.polish_rounds) break;
      limit = Math.max(limit, r + 1);
      continue;
    }
    if (r < limit) continue;

    const esc = p(`escalation-${escalations + 1}.json`);
    yield gate(`${id}/escalation-${escalations + 1}`, `${id}: review did not converge after ${r} rounds`, {
      context: [p(`review-${r}.json`), p(`checks-${r}.json`)],
      questions: [
        singleQuestion(
          'REVIEW',
          `${t.id} "${t.title}": ${rev} still requires changes after ${r} rounds (${review.summary}). Checks ${checks.passed ? 'pass' : 'FAIL'}. Answer with free text to retry with your guidance.`,
          [
            option('retry', `Retry ${ctx.config.max_review_rounds} more rounds`, 'Keep the implement/review loop going'),
            option('accept', 'Accept as-is', 'Commit the current state; findings are recorded in the report'),
            option('abort', 'Abort run', 'Stop the run here'),
          ],
          null,
        ),
      ],
      output: esc,
    });
    escalations++;
    const choice = choiceOf(esc, 'REVIEW');
    if (choice === 'accept') {
      accepted = true;
      break;
    }
    if (choice === 'abort') {
      yield aborted(id);
      return;
    }
    limit += ctx.config.max_review_rounds;
  }

  const rounds = countRounds(TD);
  yield det(`${id}/commit`, `${id}: commit`, p('commit.json'), async () => {
    // Tick the task in tasks.md in the same commit (parallel-wave tasks are ticked when merged).
    if (wt === meta.worktree && s.tasks.some((x) => x.id === t.id)) docs(ctx, s.FD, meta).tasks(s.assignment, [t.id]);
    const sha = await commitAll(
      wt,
      `feat(${meta.number}/${t.id}): ${t.title}\n\nImplemented-by: ${impl}\nReviewed-by: ${rev}\nReview-rounds: ${rounds}${accepted ? '\nAccepted-with-open-findings: yes' : ''}\nDuetto-run: ${ctx.state.id}`,
    );
    return { sha, implementer: impl, reviewer: rev, rounds, accepted_with_issues: accepted };
  });
}

// ───────────────────────────── parallel waves ─────────────────────────────

/**
 * Independent tasks, each in its own worktree branched from the feature head: one step drives all their
 * implement/review loops concurrently until each is committed or waiting on a gate; gates follow one at a time.
 * Then each task's commit is cherry-picked onto the feature branch in order; a conflicting task is redone serially.
 */
function* parallelWave(s        , wid        , wave        , assignment                           )                  {
  const { ctx, meta } = s;
  const WD = join(s.FD, 'waves', wid);
  const id = `${meta.id}/${wid}`;
  const names = wave.map((t) => t.id).join(' ∥ ');
  const taskWt = (t      ) => worktreePath(ctx.repo, ctx.config.worktrees_dir, ctx.state.id, `${meta.id}-${t.id}`);
  const taskBranch = (t      ) => `duetto/${ctx.state.id}/${meta.id}-${t.id}`;

  yield det(`${id}/setup`, `${id}: worktrees for ${names}`, join(WD, 'setup.json'), async () => {
    const base = await head(meta.worktree);
    await Promise.all(
      wave.map(async (t) => {
        if (!existsSync(taskWt(t))) await addWorktree(ctx.repo, taskWt(t), taskBranch(t), base);
        await runSetup(ctx, taskWt(t));
      }),
    );
    return { base };
  });

  const pending = (t      ) => firstPending(taskLoop(s, t, assignment[t.id], taskWt(t)));
  const runnable = (st             ) => st !== null && st.kind !== 'user';
  yield {
    id: `${id}/tasks`,
    title: `${meta.id}: tasks ${names} in parallel`,
    kind: 'worker',
    done: () => !wave.some((t) => runnable(pending(t))),
    run: async () => {
      const results = await Promise.allSettled(
        wave.map(async (t) => {
          for (let st = pending(t); st && runnable(st); st = pending(t)) {
            ctx.print(`▶ ${st.title}`);
            logEvent(ctx.dir, { type: 'step_start', step: st.id });
            await st.run ();
            if (!st.done()) throw new Error(`Step ${st.id} finished without producing its output`);
            logEvent(ctx.dir, { type: 'step_done', step: st.id });
          }
        }),
      );
      const failed = results.filter((r) => r.status === 'rejected')                           ;
      if (failed.length) throw new Error(failed.map((f) => (f.reason         ).message).join('\n'));
    },
  };
  for (const t of wave) {
    const gateStep = pending(t);
    if (gateStep) yield gateStep;
  }

  yield det(`${id}/merge`, `${id}: merge ${names} into ${meta.branch}`, join(WD, 'merge.json'), async () => {
    const merged                                                                                             = {};
    for (const t of wave) {
      // Per-task marks make the merge resumable without cherry-picking anything twice.
      const mark = join(WD, `merge-${t.id}.json`);
      if (!exists(mark)) writeJson(mark, await cherryPick(meta.worktree, readJson(join(s.FD, 'tasks', t.id, 'commit.json')).sha));
      merged[t.id] = readJson(mark);
      if (merged[t.id].status === 'conflict') ctx.print(`    ${t.id} conflicts with the merged work — it will be redone on top of it`);
      else await removeWorktree(ctx.repo, taskWt(t), taskBranch(t));
    }
    docs(ctx, s.FD, meta).tasks(s.assignment); // ticks the merged tasks; committed with the next task or the report
    return merged;
  });
  const merged = readJson(join(WD, 'merge.json'));
  for (const t of wave) {
    if (merged[t.id].status !== 'conflict') continue;
    const redo = { ...t, id: `${t.id}-rerun`, description: `${t.description}\n\n(Redo: ${t.id} was implemented in parallel with other tasks but conflicted when merged. Implement it again on top of the merged work.)` };
    yield* taskLoop(s, redo, assignment[t.id]);
  }
}

async function cherryPick(wt        , sha               ) {
  if (!sha) return { status: 'empty'          };
  const res = await exec('git', ['cherry-pick', sha], { cwd: wt });
  if (res.code === 0) return { status: 'merged'         , sha: await head(wt) };
  await exec('git', ['cherry-pick', '--abort'], { cwd: wt });
  return { status: 'conflict'         , detail: tail(res.stdout + res.stderr, 1500) };
}

/** A task merged from a parallel wave lives on the feature branch under a new sha. */
function mergedSha(FD        , taskId        )                   {
  const wavesDir = join(FD, 'waves');
  if (!existsSync(wavesDir)) return {};
  for (const w of readdirSync(wavesDir)) {
    const mark = join(wavesDir, w, `merge-${taskId}.json`);
    if (exists(mark) && readJson(mark).status === 'merged') return { sha: readJson(mark).sha };
  }
  return {};
}

function firstPending(steps                 )              {
  for (const st of steps) if (!st.done()) return st;
  return null;
}

async function runSetup(ctx     , wt        ) {
  if (!ctx.config.checks.setup) return;
  ctx.print(`    setup: ${ctx.config.checks.setup} (${wt})`);
  const res = await sh(ctx.config.checks.setup, wt, ctx.config.checks.timeout_minutes * 60_000);
  if (res.code !== 0) throw new Error(`Setup command failed in ${wt}:\n${tail(res.stdout + res.stderr, 2000)}`);
}

// ───────────────────────────── hand edits ─────────────────────────────

const ANALYSIS_FILES = ['analysis.claude.json', 'analysis.codex.json', 'analysis.json'];
const TASK_FILES = ['tasks.json', 'waves.json', 'spec-commit.json', ...ANALYSIS_FILES];
const PLAN_FILES = [
  ...['plan.claude.json', 'plan.codex.json', 'plan-rebuttal.claude.json', 'plan-rebuttal.codex.json', 'plan-synthesis.json', 'plan-decisions.json', 'plan.json'],
  ...['challenge.claude.json', 'challenge.codex.json', 'challenge-synthesis.json', 'challenge-decisions.json', 'plan-final.json'],
];

/** Moves later-phase artifacts aside so those steps run again on top of an edited document. */
function supersede(FD        , names          , why        ) {
  const present = existsSync(FD) ? readdirSync(FD).filter((n) => names.includes(n) || /^(plan|tasks)-reconcile-\d+\.json$/.test(n)) : [];
  if (!present.length) return;
  const to = join(FD, 'superseded', `${Date.now()}-${why}`);
  mkdirSync(to, { recursive: true });
  for (const n of present) renameSync(join(FD, n), join(to, n));
}

/**
 * Spec Kit users edit spec.md / plan.md / tasks.md between commands. Before implementation starts, an edited
 * document is folded back into its JSON by the host, and everything planned from the old version is redone.
 * (Once tasks are being implemented, edits are left alone; the convergence audit judges against the JSON.)
 */
function* reconcile(
  ctx     ,
  FD        ,
  meta             ,
  o                                                                                                                                                                                  ,
)                  {
  if (existsSync(join(FD, 'tasks')) || !exists(o.json) || !drifted(FD, meta, o.doc)) return;
  const base = o.doc.replace('.md', '');
  const n = readdirSync(FD).filter((x) => x.startsWith(`${base}-reconcile-`)).length + 1;
  yield host(`${meta.id}/${base}-reconcile-${n}`, `${meta.id}: apply your edits to ${o.doc}`, {
    instructions: hostInstructions('reconcile'),
    inputs: { current_json: o.json, edited_markdown: join(meta.specDir, o.doc) },
    schema: o.schema,
    output: join(FD, `${base}-reconcile-${n}.json`),
    postprocess: o.postprocess,
    after: (d) => {
      writeJson(o.json, o.wrap ? o.wrap(d) : d);
      supersede(FD, o.downstream, `${base}-edited`);
      o.render(d);
      ctx.print(`    applied your edits to ${o.doc}; later phases will be redone`);
    },
  });
}

// ───────────────────────────── decision blocks ─────────────────────────────

/** Host synthesis that may surface decisions: synth → (user decisions → host finalize) → final. */
function* decided(
  ctx     ,
  FD        ,
  meta             ,
  o                                                                                                                                                    ,
)                  {
  yield host(o.id, o.title, {
    instructions: o.instructions,
    inputs: o.inputs,
    schema: o.schema,
    output: o.synth,
    postprocess: (d) => {
      normalizeQuestions(d);
      const bounced = bounceConflicts(ctx.config, d);
      if (bounced.length) ctx.print(`    escalated to user: ${bounced.join(', ')}`);
      return d;
    },
    after: (d) => {
      if (!d.questions.length) writeJson(o.final, { plan: d.plan });
      docs(ctx, FD, meta).plan(d.plan, d);
    },
  });
  const synth = readJson(o.synth);
  if (!synth.questions.length) return;
  yield gate(`${o.id}-decisions`, `${o.title}: decisions needed`, {
    context: [join(meta.specDir, 'plan.md')],
    questions: synth.questions,
    output: o.answers,
    after: () => renderDecisionsMd(FD, meta),
  });
  yield host(`${o.id}-finalize`, `${o.title}: apply decisions`, {
    instructions: hostInstructions('finalize'),
    inputs: { synthesis: o.synth, decisions: o.answers },
    schema: 'PlanFinal',
    output: o.final,
    after: (d) => docs(ctx, FD, meta).plan(d.plan, synth),
  });
}

// ───────────────────────────── small helpers ─────────────────────────────

function aborted(id        )       {
  return {
    id: `${id}/aborted`,
    title: 'Aborted by user',
    kind: 'deterministic',
    done: () => false,
    run: async () => {
      throw new Error(`Run aborted by user at ${id}`);
    },
  };
}

function validateTasks(d                   ) {
  if (!d.tasks.length) throw new Error('At least one task is required');
  if (new Set(d.tasks.map((t) => t.id)).size !== d.tasks.length) throw new Error('Duplicate task ids');
  topoSort(d.tasks);
  return d;
}

function pick(o                               )                         {
  return Object.fromEntries(Object.entries(o).filter(([, v]) => v))                          ;
}

function normalizeQuestions(d                          ) {
  const ids = new Set        ();
  for (const q of d.questions) {
    if (ids.has(q.id)) throw new Error(`Duplicate question id ${q.id}`);
    ids.add(q.id);
    if (q.suggested && !q.options.some((o) => o.key === q.suggested)) throw new Error(`${q.id}: suggested "${q.suggested}" is not an option key`);
  }
  return d;
}

function answerFiles(FD        )           {
  if (!existsSync(FD)) return [];
  return readdirSync(FD)
    .filter((n) => /^answers-\d+\.json$/.test(n) || /-decisions\.json$/.test(n))
    .map((n) => join(FD, n));
}

function answerInputs(FD        , beforeRound = Infinity)                         {
  return Object.fromEntries(
    answerFiles(FD)
      .filter((f) => {
        const m = f.match(/answers-(\d+)\.json$/);
        return !m || Number(m[1]) < beforeRound;
      })
      .map((f) => [`user_${f.split('/').pop() .replace('.json', '')}`, f]),
  );
}

function allAnswers(FD        ) {
  return answerFiles(FD).map((f) => readJson(f));
}

function renderDecisionsMd(FD        , meta             ) {
  const entries = answerFiles(FD).map((f) => {
    const d = readJson(f);
    return { phase: f.split('/').pop() .replace('.json', ''), questions: d.questions, answers: d.answers };
  });
  writeText(join(meta.specDir, 'decisions.md'), render.renderDecisions(entries));
}

function renderAll(ctx     , FD        , meta             , finalPlan        , assignment                        ) {
  const doc = docs(ctx, FD, meta);
  writeText(join(meta.specDir, 'research.md'), render.renderResearch(readJson(join(FD, 'research.json'))));
  doc.spec();
  const synth = exists(join(FD, 'challenge-synthesis.json')) ? readJson(join(FD, 'challenge-synthesis.json')) : {};
  const planSynth = readJson(join(FD, 'plan-synthesis.json'));
  doc.plan(readJson(finalPlan).plan, { conflicts: planSynth.conflicts, accepted: synth.accepted, rejected: synth.rejected });
  if (exists(join(FD, 'tasks.json'))) doc.tasks(assignment);
  renderDecisionsMd(FD, meta);
}

function escalationGuidance(TD        , count        )           {
  const out           = [];
  for (let i = 1; i <= count; i++) {
    const c = choiceOf(join(TD, `escalation-${i}.json`), 'REVIEW');
    if (c && !['retry', 'accept', 'abort'].includes(c)) out.push(c);
  }
  return out;
}

function summarizeChecks(c             ) {
  return {
    failing_commands: c.commands.filter((x) => x.exit_code !== 0).map((x) => ({ cmd: x.cmd, output_tail: x.output_tail })),
    protected_violations: c.protected_violations,
  };
}

/** Checks as agents see them: passing commands are just a name and exit code, failing ones keep their output. */
function checksForPrompt(c             ) {
  return { ...c, commands: c.commands.map((x) => (x.exit_code === 0 ? { cmd: x.cmd, exit_code: 0 } : x)) };
}

/** Critical/high findings of the pre-implementation analysis, if one ran: every implementer should respect them. */
function seriousAnalysis(FD        ) {
  const path = join(FD, 'analysis.json');
  if (!exists(path)) return null;
  const serious = readJson(path).findings.filter((x     ) => x.severity === 'critical' || x.severity === 'high');
  return serious.length ? serious : null;
}

function hasPolishFindings(review     , severities          )          {
  return review.status === 'approved' && review.findings.some((f     ) => severities.includes(f.severity));
}

/** Number of rounds before `upTo` (inclusive) whose approved review triggered a polish round. */
function countPolishRounds(TD        , upTo        , severities          )         {
  let n = 0;
  for (let i = 1; i <= upTo; i++) {
    const p = join(TD, `review-${i}.json`);
    if (exists(p) && hasPolishFindings(readJson(p), severities)) n++;
  }
  return n;
}

function countRounds(TD        )         {
  return existsSync(TD) ? readdirSync(TD).filter((n) => /^impl-\d+\.json$/.test(n)).length : 0;
}

function lastNumbered(dir        , prefix        , suffix        , filter                         = () => true)                {
  const names = readdirSync(dir).filter((n) => n.startsWith(prefix) && n.endsWith(suffix) && filter(n));
  if (!names.length) return null;
  names.sort((a, b) => Number(a.slice(prefix.length).split(/\D/)[0]) - Number(b.slice(prefix.length).split(/\D/)[0]));
  return join(dir, names[names.length - 1]);
}
