// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { readText } from './util.mjs';

const PROMPTS = join(import.meta.dirname, '..', 'prompts');
export const promptPath = (name        ) => join(PROMPTS, `${name}.md`);
export const loadPrompt = (name        ) => readFileSync(promptPath(name), 'utf8').trim();

export function constitution(repo        )         {
  return readText(join(repo, '.duetto', 'constitution.md'), '(no constitution defined)').trim();
}

/** Inputs are embedded verbatim so both models receive byte-identical context. */
export function workerPrompt(role        , repo        , inputs                         , extra = '')         {
  const blocks = Object.entries(inputs)
    .filter(([, v]) => v !== undefined && v !== null)
    .map(([name, v]) => `<input name="${name}">\n${typeof v === 'string' ? v : JSON.stringify(v, null, 2)}\n</input>`)
    .join('\n\n');
  return [
    loadPrompt('_worker'),
    loadPrompt(role),
    `# Engineering constitution\n${constitution(repo)}`,
    `# Inputs\n${blocks}`,
    extra && `# Additional instructions\n${extra}`,
    '# Output\nReturn only the JSON object described by the schema.',
  ]
    .filter(Boolean)
    .join('\n\n');
}

export function hostInstructions(step        , extra = '')         {
  return [loadPrompt('host/_common'), loadPrompt(`host/${step}`), extra].filter(Boolean).join('\n\n');
}
