// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
// Minimal JSON-Schema builders + validator. Every object is "strict" (all properties required,
// no extras) because Codex --output-schema requires it; optional values are expressed as nullable.

                                          

const d = (description         ) => (description ? { description } : {});

export const str = (description         )         => ({ type: 'string', ...d(description) });
export const nstr = (description         )         => ({ type: ['string', 'null'], ...d(description) });
export const int = (description         )         => ({ type: 'integer', ...d(description) });
export const nint = (description         )         => ({ type: ['integer', 'null'], ...d(description) });
export const num = (description         )         => ({ type: 'number', ...d(description) });
export const bool = (description         )         => ({ type: 'boolean', ...d(description) });
export const arr = (items        , description         )         => ({ type: 'array', items, ...d(description) });
export const strs = (description         )         => arr(str(), description);
export const enm = (values                   , description         )         => ({
  type: 'string',
  enum: [...values],
  ...d(description),
});
export const nenm = (values                   , description         )         => ({
  type: ['string', 'null'],
  enum: [...values, null],
  ...d(description),
});
export const obj = (properties                        , description         )         => ({
  type: 'object',
  properties,
  required: Object.keys(properties),
  additionalProperties: false,
  ...d(description),
});

function typeOf(v         )         {
  if (v === null) return 'null';
  if (Array.isArray(v)) return 'array';
  if (typeof v === 'number') return Number.isInteger(v) ? 'integer' : 'number';
  return typeof v;
}

export function validate(schema        , value         , path = '$')           {
  if (schema.anyOf) {
    const results = (schema.anyOf            ).map((s) => validate(s, value, path));
    return results.some((r) => r.length === 0) ? [] : results.sort((a, b) => a.length - b.length)[0];
  }
  const errors           = [];
  const types           = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  const actual = typeOf(value);
  if (types.length && !types.includes(actual) && !(actual === 'integer' && types.includes('number'))) {
    return [`${path}: expected ${types.join('|')}, got ${actual}`];
  }
  if (schema.enum && !schema.enum.includes(value)) {
    errors.push(`${path}: must be one of ${schema.enum.map((e         ) => JSON.stringify(e)).join(', ')}`);
  }
  if (actual === 'array' && schema.items) {
    (value             ).forEach((item, i) => errors.push(...validate(schema.items, item, `${path}[${i}]`)));
  }
  if (actual === 'object' && schema.properties) {
    const v = value                           ;
    for (const key of schema.required ?? []) {
      if (!(key in v)) errors.push(`${path}.${key}: required`);
    }
    for (const [key, val] of Object.entries(v)) {
      const sub = schema.properties[key];
      if (sub) errors.push(...validate(sub, val, `${path}.${key}`));
      else if (schema.additionalProperties === false) errors.push(`${path}.${key}: unexpected property`);
    }
  }
  return errors;
}

/** Parse model text output into JSON, tolerating ```json fences and leading prose. */
export function parseJsonLoose(text        )          {
  const trimmed = text.trim();
  try {
    return JSON.parse(trimmed);
  } catch {}
  const fence = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fence) {
    try {
      return JSON.parse(fence[1]);
    } catch {}
  }
  const start = trimmed.indexOf('{');
  const end = trimmed.lastIndexOf('}');
  if (start >= 0 && end > start) return JSON.parse(trimmed.slice(start, end + 1));
  throw new Error('Output is not JSON');
}
