// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
// Spec Kit interop: use a project's .specify/ (templates, constitution, current feature) when it has one.
// Duetto never creates .specify/ itself — `specify init` owns it — so without one it falls back to its own files.

import { readdirSync } from 'node:fs';
import { join } from 'node:path';
import { exec, exists, readJson, readText, writeJson } from './util.mjs';

                                                                           

const specify = (repo        , ...p          ) => join(repo, '.specify', ...p);
const BUNDLED = join(import.meta.dirname, '..', 'templates', 'speckit');

export function detect(repo        )              {
  if (!exists(specify(repo))) return { present: false, integration: null };
  let integration                = null;
  try {
    const j = readJson(specify(repo, 'integration.json'));
    integration = j.default_integration ?? j.integration ?? null;
  } catch {}
  return { present: true, integration };
}

/** The engineering constitution every agent gets: Spec Kit's when the project has one, else duetto's. */
export function constitutionPath(repo        )         {
  const sk = specify(repo, 'memory', 'constitution.md');
  return exists(sk) ? sk : join(repo, '.duetto', 'constitution.md');
}

                                                                                

/**
 * A Spec Kit template, resolved the way Spec Kit does it. Its own resolve-template.sh (overrides, presets,
 * extensions) is used when present; otherwise overrides → .specify/templates → duetto's bundled copy.
 */
export async function resolveTemplate(repo        , name              )                  {
  const script = specify(repo, 'scripts', 'bash', 'resolve-template.sh');
  if (exists(script)) {
    const res = await exec('bash', [script, name], { cwd: repo, timeoutMs: 15_000 });
    if (res.code === 0 && res.stdout.trim()) return res.stdout;
  }
  for (const p of [specify(repo, 'templates', 'overrides', `${name}.md`), specify(repo, 'templates', `${name}.md`), join(BUNDLED, `${name}.md`)]) {
    if (exists(p)) return readText(p);
  }
  throw new Error(`No ${name} found`);
}

/** The current feature dir from .specify/feature.json (repo-relative, as Spec Kit stores it), or null. */
export function readFeatureDir(repo        )                {
  try {
    return readJson(specify(repo, 'feature.json')).feature_directory || null;
  } catch {
    return null;
  }
}

/** Point Spec Kit's commands at a feature dir. A no-op without .specify/. */
export function writeFeatureDir(repo        , featureDir        )       {
  if (!exists(specify(repo))) return;
  const rel = featureDir.startsWith(repo + '/') ? featureDir.slice(repo.length + 1) : featureDir;
  writeJson(specify(repo, 'feature.json'), { feature_directory: rel });
}

/** Next sequential feature number under specs/, as Spec Kit counts them (3+ digits; timestamp dirs ignored). */
export function nextFeatureNumber(specsRoot        )         {
  const used = exists(specsRoot)
    ? readdirSync(specsRoot)
        .filter((n) => /^\d{3,}-/.test(n) && !/^\d{8}-\d{6}-/.test(n))
        .map((n) => Number(n.match(/^(\d+)-/) [1]))
    : [];
  return String(Math.max(0, ...used) + 1).padStart(3, '0');
}
