// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
import { join } from 'node:path';
import { codexActivity } from '../activity.mjs';
import { exec, exists, readText, tail, writeJson, writeText } from '../util.mjs';
import { resolveAgent,                  } from '../config.mjs';
                                                                
import { childEnv } from './claude.mjs';

export class CodexAgent                  {
  name = 'codex'         ;
          cfg             ;
  constructor(cfg             ) {
    this.cfg = cfg;
  }

  async invoke(call           )                       {
    const { model, effort } = resolveAgent(this.cfg, call.role);
    const schemaPath = join(call.rawDir, `${call.label}.schema.json`);
    const outPath = join(call.rawDir, `${call.label}.last.json`);
    writeJson(schemaPath, call.schema);
    const args = [
      'exec',
      '-m',
      model,
      '-c',
      `model_reasoning_effort="${effort}"`,
      // Without summaries, codex --json emits no reasoning items and the live view shows no thinking.
      '-c',
      'model_reasoning_summary="detailed"',
      '-C',
      call.cwd,
      '-s',
      call.writable ? 'workspace-write' : 'read-only',
      '--skip-git-repo-check',
      '--ephemeral',
      '--output-schema',
      schemaPath,
      '-o',
      outPath,
      '--json',
      '-',
    ];
    const cmd = this.cfg.command ?? 'codex';
    writeText(join(call.rawDir, `${call.label}.argv.json`), JSON.stringify([cmd, ...args], null, 2));
    const onStdoutLine = (line        ) => {
      try {
        for (const a of codexActivity(JSON.parse(line), call.cwd)) call.onActivity?.(a);
      } catch {}
    };
    const res = await exec(cmd, args, { cwd: call.cwd, input: call.prompt, timeoutMs: call.timeoutMs, env: childEnv(), onStdoutLine });
    writeText(join(call.rawDir, `${call.label}.events.jsonl`), res.stdout);
    if (res.stderr) writeText(join(call.rawDir, `${call.label}.stderr.txt`), res.stderr);
    if (res.timedOut) throw new Error(`codex timed out after ${Math.round(call.timeoutMs / 60000)}m`);
    if (res.code !== 0 || !exists(outPath)) {
      throw new Error(`codex exited ${res.code}: ${tail(res.stderr || lastError(res.stdout), 800)}`);
    }
    return { text: readText(outPath), raw: res.stdout };
  }
}

function lastError(jsonl        )         {
  const lines = jsonl.trim().split('\n').reverse();
  for (const l of lines) {
    try {
      const e = JSON.parse(l);
      const msg = e?.msg?.message ?? e?.message ?? e?.error?.message;
      if (msg) return String(msg);
    } catch {}
  }
  return tail(jsonl, 800);
}
