// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
import { join } from 'node:path';
import { parseJsonLoose, validate } from '../schema.mjs';
import { writeText } from '../util.mjs';
                                           
                                               
import { ClaudeAgent } from './claude.mjs';
import { CodexAgent } from './codex.mjs';
                                                   

                                              

export function createAgents(config        )         {
  return { claude: new ClaudeAgent(config.agents.claude), codex: new CodexAgent(config.agents.codex) };
}

export const other = (a           )            => (a === 'claude' ? 'codex' : 'claude');

                                                                                               

/** Invoke an agent, validate against the schema, and retry once with the validation errors appended. */
export async function runAgent(agent       , call           )                    {
  const started = Date.now();
  let prompt = call.prompt;
  let lastErrors           = [];
  let cost = 0;
  for (let attempt = 1; attempt <= 2; attempt++) {
    const label = attempt === 1 ? call.label : `${call.label}.retry`;
    writeText(join(call.rawDir, `${label}.prompt.md`), prompt);
    const out = await agent.invoke({ ...call, prompt, label });
    cost += out.costUsd ?? 0;
    let value         ;
    try {
      value = out.structured ?? parseJsonLoose(out.text);
      lastErrors = validate(call.schema, value);
    } catch (err) {
      lastErrors = [(err         ).message];
    }
    if (lastErrors.length === 0) {
      return { output: value, durationMs: Date.now() - started, costUsd: cost || undefined, attempts: attempt };
    }
    call.onActivity?.({ kind: 'retry', text: `output did not match the schema (${lastErrors.length} errors) — asking again` });
    prompt =
      call.prompt +
      `\n\n---\nYour previous response did not match the required JSON schema:\n${lastErrors.slice(0, 30).join('\n')}\n` +
      `Respond again with a single JSON object that matches the schema exactly.`;
  }
  throw new Error(`${agent.name} output failed schema validation twice:\n${lastErrors.slice(0, 15).join('\n')}`);
}
