// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
import { join } from 'node:path';
import { exec, tail, writeText } from '../util.mjs';
import { resolveAgent,                  } from '../config.mjs';
                                                                

const READ_TOOLS = ['Read', 'Glob', 'Grep', 'Bash', 'WebSearch', 'WebFetch'];
// Read-only roles may run any command (tests, probes) but inside Claude Code's OS sandbox, which
// denies writes to the working tree; temp dirs stay writable so test runners still work.
const READ_ALLOWED = ['Read', 'Glob', 'Grep', 'WebSearch', 'WebFetch', 'Bash'];

export function readOnlySandbox(cwd        ) {
  return { sandbox: { enabled: true, autoAllowBashIfSandboxed: true, allowUnsandboxedCommands: false, filesystem: { denyWrite: [cwd] } } };
}
const WRITE_TOOLS = ['Read', 'Glob', 'Grep', 'Bash', 'Edit', 'Write', 'WebSearch', 'WebFetch'];

export function childEnv()                    {
  const env = { ...process.env };
  // Allow launching `claude -p` from inside a Claude Code session.
  delete env.CLAUDECODE;
  delete env.CLAUDE_CODE_ENTRYPOINT;
  return env;
}

export class ClaudeAgent                  {
  name = 'claude'         ;
          cfg             ;
  constructor(cfg             ) {
    this.cfg = cfg;
  }

  async invoke(call           )                       {
    const { model, effort } = resolveAgent(this.cfg, call.role);
    const args = [
      '-p',
      '--output-format',
      'json',
      '--json-schema',
      JSON.stringify(call.schema),
      '--model',
      model,
      '--effort',
      effort,
      '--no-session-persistence',
    ];
    if (call.writable) {
      args.push('--tools', WRITE_TOOLS.join(','), '--allowedTools', WRITE_TOOLS.join(','), '--permission-mode', 'acceptEdits');
    } else {
      args.push(
        '--tools',
        READ_TOOLS.join(','),
        '--allowedTools',
        READ_ALLOWED.join(','),
        '--disallowedTools',
        'Edit,Write,NotebookEdit',
        '--settings',
        JSON.stringify(readOnlySandbox(call.cwd)),
      );
    }
    const cmd = this.cfg.command ?? 'claude';
    writeText(join(call.rawDir, `${call.label}.argv.json`), JSON.stringify([cmd, ...args.map((a) => (a.length > 300 ? a.slice(0, 300) + '…' : a))], null, 2));
    const res = await exec(cmd, args, { cwd: call.cwd, input: call.prompt, timeoutMs: call.timeoutMs, env: childEnv() });
    writeText(join(call.rawDir, `${call.label}.stdout.json`), res.stdout);
    if (res.stderr) writeText(join(call.rawDir, `${call.label}.stderr.txt`), res.stderr);
    if (res.timedOut) throw new Error(`claude timed out after ${Math.round(call.timeoutMs / 60000)}m`);

    let parsed     ;
    try {
      parsed = JSON.parse(res.stdout);
    } catch {
      throw new Error(`claude exited ${res.code} without JSON output: ${tail(res.stderr || res.stdout, 800)}`);
    }
    if (res.code !== 0 || parsed.is_error) {
      throw new Error(`claude failed (${parsed.subtype ?? res.code}): ${tail(String(parsed.result ?? res.stderr), 800)}`);
    }
    return { text: String(parsed.result ?? ''), structured: parsed.structured_output, costUsd: parsed.total_cost_usd, raw: res.stdout };
  }
}
