#!/usr/bin/env node
// Zero-dependency build: strips TypeScript types from src/**/*.ts with Node's built-in
// module.stripTypeScriptTypes and writes plain ESM (.mjs) into the plugin's skill directory,
// so installs from git need no build step and run on Node versions without type stripping.
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import { dirname, join, relative } from 'node:path';

process.removeAllListeners('warning'); // stripTypeScriptTypes is experimental; the warning is noise here
const root = join(import.meta.dirname, '..');
const out = join(root, 'plugins', 'duet', 'skills', 'duet', 'engine');
const banner = '// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.\n';

const toMjs = (code) => code.replace(/(from\s+|import\s*\(\s*|import\s+)(['"])(\.{1,2}\/[^'"]+)\.ts\2/g, '$1$2$3.mjs$2');

function walk(dir) {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

rmSync(out, { recursive: true, force: true });
let files = 0;
for (const file of walk(join(root, 'src')).filter((f) => f.endsWith('.ts'))) {
  const dest = join(out, 'src', relative(join(root, 'src'), file)).replace(/\.ts$/, '.mjs');
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, banner + toMjs(stripTypeScriptTypes(readFileSync(file, 'utf8'), { mode: 'strip' })));
  files++;
}
mkdirSync(join(out, 'bin'), { recursive: true });
writeFileSync(join(out, 'bin', 'duet.mjs'), readFileSync(join(root, 'bin', 'duet.js'), 'utf8').replace("'../src/cli.ts'", "'../src/cli.mjs'"));
cpSync(join(root, 'prompts'), join(out, 'prompts'), { recursive: true });
cpSync(join(root, 'templates'), join(out, 'templates'), { recursive: true });
writeFileSync(join(out, 'package.json'), JSON.stringify({ type: 'module', private: true }, null, 2) + '\n');
console.log(`built ${files} modules → ${relative(root, out)}`);
