#!/usr/bin/env node
// Zero-dependency build: strips TypeScript types from src/**/*.ts with Node's built-in
// module.stripTypeScriptTypes and writes plain ESM (.mjs) into the plugin's skill directory,
// so installs from git need no build step and run on Node versions without type stripping.
import { chmodSync, cpSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import { dirname, join, relative } from 'node:path';

process.removeAllListeners('warning'); // stripTypeScriptTypes is experimental; the warning is noise here
const root = join(import.meta.dirname, '..');
const out = join(root, 'plugins', 'duetto', 'skills', 'duetto', 'engine');
const banner = '// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.\n';

const toMjs = (code) => code.replace(/(from\s+|import\s*\(\s*|import\s+)(['"])(\.{1,2}\/[^'"]+)\.ts\2/g, '$1$2$3.mjs$2');

function walk(dir) {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

rmSync(out, { recursive: true, force: true });
let files = 0;
for (const file of walk(join(root, 'src')).filter((f) => f.endsWith('.ts'))) {
  const dest = join(out, 'src', relative(join(root, 'src'), file)).replace(/\.ts$/, '.mjs');
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, banner + toMjs(stripTypeScriptTypes(readFileSync(file, 'utf8'), { mode: 'strip' })));
  files++;
}
mkdirSync(join(out, 'bin'), { recursive: true });
writeFileSync(join(out, 'bin', 'duetto.mjs'), readFileSync(join(root, 'bin', 'duetto.js'), 'utf8').replace("'../src/cli.ts'", "'../src/cli.mjs'"));
cpSync(join(root, 'prompts'), join(out, 'prompts'), { recursive: true });
cpSync(join(root, 'templates'), join(out, 'templates'), { recursive: true });
writeFileSync(join(out, 'package.json'), JSON.stringify({ type: 'module', private: true }, null, 2) + '\n');
console.log(`built ${files} modules → ${relative(root, out)}`);

// ── Per-command entry points, generated from packaging/commands.json:
//    plugin skills /duetto-<cmd> (Claude Code + Codex) and a Spec Kit extension (/speckit-duetto-<cmd>).
const commands = JSON.parse(readFileSync(join(root, 'packaging', 'commands.json'), 'utf8'));
const skillsDir = join(root, 'plugins', 'duetto', 'skills');
for (const d of readdirSync(skillsDir)) if (d.startsWith('duetto-')) rmSync(join(skillsDir, d), { recursive: true });
const title = (c) => c.name[0].toUpperCase() + c.name.slice(1);
const nextOf = (c, prefix) =>
  c.name === 'tasks'
    ? `\`${prefix}implement\` (optionally \`${prefix}analyze\` first)`
    : c.next
      ? `\`${prefix}${c.next}\``
      : 'nothing: the feature is done; offer to open a PR';

for (const c of commands) {
  const dir = join(skillsDir, `duetto-${c.name}`);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, 'SKILL.md'),
    `---
name: duetto-${c.name}
description: Duetto ${c.name} (Claude + Codex, Spec Kit-style). ${c.summary} Use when the user invokes /duetto-${c.name} or $duetto-${c.name}, or asks to ${c.ask} with both Claude and Codex.
---
<!-- Generated by scripts/build.mjs from packaging/commands.json. Do not edit. -->

# Duetto: ${c.name}

${c.summary}

1. The engine is in the sibling \`duetto\` skill: \`duetto\` below means \`node "<skill-dir>/../duetto/engine/bin/duetto.mjs"\`
   (\`<skill-dir>\` is this file's directory).
2. Run \`duetto ${c.name} ${c.args} --detach\`, passing along what the user gave you.
3. Drive the run exactly as \`<skill-dir>/../duetto/reference/loop.md\` describes until its status is \`paused\` (this
   phase is complete) or \`done\`: synthesis steps, questions for the user, failures, everything.
4. Then tell the user what the phase produced, linking the files under \`specs/NNN-*/\` (${c.produces}), and that
   the next step is ${nextOf(c, '/duetto-')}.
`,
  );
}

const ext = join(root, 'speckit', 'duetto');
rmSync(ext, { recursive: true, force: true });
mkdirSync(join(ext, 'commands'), { recursive: true });
mkdirSync(join(ext, 'scripts', 'bash'), { recursive: true });
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const loop = readFileSync(join(skillsDir, 'duetto', 'reference', 'loop.md'), 'utf8').replace(/^# .*\n+/, '');
const script = '.specify/extensions/duetto/scripts/bash/duetto.sh';
writeFileSync(
  join(ext, 'extension.yml'),
  `# Generated by scripts/build.mjs from packaging/commands.json. Do not edit.
schema_version: "1.0"
extension:
  id: duetto
  name: "Duetto (Claude + Codex)"
  version: "${pkg.version}"
  description: "Every Spec Kit phase run by both Claude and Codex: independent research, plans, rebuttals and cross-review"
  author: "Bishoy Gendy"
  repository: "https://github.com/bishoyngendy/duetto"
  license: MIT
requires:
  speckit_version: ">=1.0.0"
  tools:
    - name: node
      required: true
    - name: claude
      required: true
    - name: codex
      required: true
provides:
  commands:
${commands.map((c) => `    - name: speckit.duetto.${c.name}\n      file: commands/speckit.duetto.${c.name}.md\n      description: ${JSON.stringify(c.summary)}`).join('\n')}
  scripts:
    - name: duetto
      file: scripts/bash/duetto.sh
      description: "Runs the Duetto engine installed with the duetto plugin"
      runtimes: [bash]
hooks:
  after_tasks:
    command: speckit.duetto.analyze
    optional: true
    prompt: "Have Claude and Codex both audit spec, plan and tasks (duetto analyze)?"
    description: "Dual-model consistency analysis"
tags: [multi-agent, claude, codex, review]
`,
);
for (const c of commands) {
  writeFileSync(
    join(ext, 'commands', `speckit.duetto.${c.name}.md`),
    `---
description: ${JSON.stringify(`${c.summary} (Claude + Codex, via Duetto)`)}
---
<!-- Generated by scripts/build.mjs from packaging/commands.json. Do not edit. -->

# Duetto: ${c.name}

${c.summary}

## User Input

$ARGUMENTS

## Steps

1. Run \`${script} ${c.name} ${c.args} --detach\` with the user's input. In what follows, \`duetto\` means \`${script}\`.
2. Drive the run as described below until its status is \`paused\` (this phase is complete) or \`done\`.
3. Tell the user what the phase produced, linking the files under \`specs/NNN-*/\` (${c.produces}), and that the next
   step is ${nextOf(c, '/speckit-duetto-')}.

${loop}`,
  );
}
cpSync(join(root, 'packaging', 'speckit', 'duetto.sh'), join(ext, 'scripts', 'bash', 'duetto.sh'));
chmodSync(join(ext, 'scripts', 'bash', 'duetto.sh'), 0o755);
cpSync(join(root, 'LICENSE'), join(ext, 'LICENSE'));
writeFileSync(
  join(ext, 'README.md'),
  `<!-- Generated by scripts/build.mjs. Do not edit. -->
# Duetto for Spec Kit

Runs each Spec Kit phase with **both Claude and Codex**: independent research and plans, rebuttals, adversarial
challenge, and implementation where one model writes and the other reviews. Install the duetto plugin (it carries the
engine) and this extension:

\`\`\`sh
claude plugin marketplace add bishoyngendy/duetto && claude plugin install duetto@duetto   # or the Codex plugin
git clone https://github.com/bishoyngendy/duetto && specify extension add --dev duetto/speckit/duetto
\`\`\`

| Command | What it does |
|---|---|
${commands.map((c) => `| \`/speckit-duetto-${c.name}\` | ${c.summary} |`).join('\n')}
`,
);
console.log(`generated ${commands.length} command skills and the Spec Kit extension`);
