// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
import { mkdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { runAgent } from './agents/index.mjs';
import { pipeline,                     } from './pipeline.mjs';
import { validate } from './schema.mjs';
import { SCHEMAS,                           } from './schemas.mjs';
import { acquireLock, logEvent, saveState } from './state.mjs';
import { appendLine, exists, writeJson } from './util.mjs';

export function locate(ctx     )                                      {
  const done         = [];
  for (const step of pipeline(ctx)) {
    if (step.done()) done.push(step);
    else return { step, done };
  }
  return { step: null, done };
}

function setStatus(ctx     , status                        , step             , message                = null) {
  ctx.state.status = status;
  ctx.state.step = step ? { id: step.id, title: step.title, kind: step.kind } : null;
  ctx.state.message = message;
  saveState(ctx.dir, ctx.state);
}

/** Advance until a host step, a user gate, completion or failure. */
export async function advance(ctx     , opts                                            = {})                                  {
  const release = acquireLock(ctx.dir);
  let steps = 0;
  try {
    for (;;) {
      const { step } = locate(ctx);
      if (!step) {
        setStatus(ctx, 'done', null, 'All features complete.');
        logEvent(ctx.dir, { type: 'done' });
        ctx.print('✔ run complete');
        return 'done';
      }
      if (opts.maxSteps !== undefined && steps++ >= opts.maxSteps) {
        setStatus(ctx, 'idle', step);
        return 'idle';
      }
      if (step.kind === 'user') {
        setStatus(ctx, 'needs_answers', step);
        logEvent(ctx.dir, { type: 'gate', step: step.id });
        ctx.print(`⏸ ${step.title} — waiting for your answers (orch next)`);
        return 'needs_answers';
      }
      if (step.kind === 'host' && !opts.headless) {
        setStatus(ctx, 'needs_synthesis', step);
        logEvent(ctx.dir, { type: 'host', step: step.id });
        ctx.print(`⏸ ${step.title} — waiting for the orchestrator session (orch next)`);
        return 'needs_synthesis';
      }
      setStatus(ctx, 'running', step);
      ctx.print(`▶ ${step.title}`);
      logEvent(ctx.dir, { type: 'step_start', step: step.id });
      if (step.kind === 'host') await runHostHeadless(ctx, step);
      else await step.run ();
      if (!step.done()) throw new Error(`Step ${step.id} finished without producing its output`);
      logEvent(ctx.dir, { type: 'step_done', step: step.id });
    }
  } catch (err) {
    const message = (err         ).message;
    const { step } = safeLocate(ctx);
    setStatus(ctx, 'failed', step, message);
    logEvent(ctx.dir, { type: 'failed', step: step?.id, message });
    ctx.print(`✖ ${message}\n  Fix the cause and run \`orch run\` again — completed work is kept.`);
    return 'failed';
  } finally {
    release();
  }
}

function safeLocate(ctx     ) {
  try {
    return locate(ctx);
  } catch {
    return { step: null, done: [] };
  }
}

export function hostTaskView(ctx     , step      ) {
  const h = step.host ;
  const schemaPath = join(ctx.dir, 'schemas', `${h.schema}.json`);
  writeJson(schemaPath, SCHEMAS[h.schema]);
  const draftPath = join(ctx.dir, 'host', `${step.id.replace(/[^\w.-]+/g, '__')}.json`);
  mkdirSync(dirname(draftPath), { recursive: true });
  return {
    kind: 'host'         ,
    step: step.id,
    title: step.title,
    instructions: h.instructions,
    inputs: h.inputs,
    schema: h.schema,
    schema_path: schemaPath,
    draft_path: draftPath,
  };
}

export function gateView(ctx     , step      ) {
  return { kind: 'user'         , step: step.id, title: step.title, context: step.gate .context, questions: step.gate .questions };
}

/** Accept the host's synthesis for the current host step. Throws with validation errors. */
export async function submit(ctx     , file        )                {
  const { step } = locate(ctx);
  if (!step || step.kind !== 'host') throw new Error(`No host step is pending (current: ${step?.id ?? 'none'})`);
  let data     ;
  try {
    data = JSON.parse(readFileSync(file, 'utf8'));
  } catch (err) {
    throw new Error(`Cannot parse ${file}: ${(err         ).message}`);
  }
  await acceptHostOutput(ctx, step, data);
  logEvent(ctx.dir, { type: 'submit', step: step.id, by: 'host' });
  setStatus(ctx, 'idle', null);
  return step;
}

async function acceptHostOutput(ctx     , step      , data     ) {
  const h = step.host ;
  const errors = validate(SCHEMAS[h.schema], data);
  if (errors.length) throw new Error(`Submission does not match schema ${h.schema}:\n${errors.slice(0, 30).join('\n')}`);
  const final = h.postprocess ? h.postprocess(data) : data;
  writeJson(h.output, final);
  await h.after?.(final);
}

async function runHostHeadless(ctx     , step      ) {
  const h = step.host ;
  const agent = ctx.config.synthesizer_fallback;
  const inputs = Object.entries(h.inputs)
    .map(([name, path]) => `<input name="${name}">\n${exists(path) ? readFileSync(path, 'utf8') : '(missing)'}\n</input>`)
    .join('\n\n');
  const prompt = `${h.instructions}\n\n(You are running headless: return the JSON directly instead of submitting a file.)\n\n# Inputs\n${inputs}\n\n# Output\nReturn only the JSON object described by the schema.`;
  ctx.print(`    ${agent} ▸ synthesizer (headless)…`);
  const res = await runAgent(ctx.agents[agent], {
    role: 'synthesizer',
    prompt,
    cwd: ctx.repo,
    writable: false,
    schema: SCHEMAS[h.schema],
    rawDir: join(ctx.dir, 'raw'),
    label: `${step.id.replace(/[^\w.-]+/g, '__')}.host-${agent}`,
    timeoutMs: ctx.config.timeout_minutes * 60_000,
  });
  await acceptHostOutput(ctx, step, res.output);
  logEvent(ctx.dir, { type: 'submit', step: step.id, by: agent, duration_ms: res.durationMs, cost_usd: res.costUsd });
}

/**
 * Record answers for the pending gate. `given` maps question id → option key or free text.
 * With acceptSuggested, unanswered questions take their suggested (consensus) option.
 */
export async function answer(ctx     , given                        , acceptSuggested = false)                    {
  const { step } = locate(ctx);
  if (!step || step.kind !== 'user') throw new Error(`No question gate is pending (current: ${step?.id ?? 'none'})`);
  const qs            = step.gate .questions;
  const unknown = Object.keys(given).filter((id) => !qs.some((q) => q.id === id));
  if (unknown.length) throw new Error(`Unknown question id(s): ${unknown.join(', ')}. Pending: ${qs.map((q) => q.id).join(', ')}`);
  const answers           = [];
  const missing           = [];
  for (const q of qs) {
    const raw = given[q.id] ?? (acceptSuggested ? (q.suggested ?? undefined) : undefined);
    if (raw === undefined || raw === '') {
      missing.push(q.id);
      continue;
    }
    const opt = q.options.find((o) => o.key.toLowerCase() === raw.toLowerCase());
    answers.push({ id: q.id, question: q.text, choice: opt ? opt.key : raw, label: opt ? `${opt.key}: ${opt.label}` : raw });
  }
  if (missing.length) throw new Error(`Missing answers for: ${missing.join(', ')}`);
  writeJson(step.gate .output, { questions: qs, answers });
  appendLine(join(ctx.dir, 'decisions.jsonl'), JSON.stringify({ step: step.id, answers }));
  await step.gate .after?.(answers);
  logEvent(ctx.dir, { type: 'answer', step: step.id, answers: answers.map((a) => ({ id: a.id, choice: a.choice })) });
  setStatus(ctx, 'idle', null);
  return answers;
}

export function costSummary(dir        ) {
  const p = join(dir, 'events.jsonl');
  const totals                                                              = {};
  if (!exists(p)) return totals;
  for (const line of readFileSync(p, 'utf8').split('\n')) {
    if (!line) continue;
    const e = JSON.parse(line);
    const who = e.type === 'agent' ? e.agent : e.type === 'submit' && e.by !== 'host' ? e.by : null;
    if (!who) continue;
    const t = (totals[who] ??= { calls: 0, cost: 0, ms: 0 });
    t.calls++;
    t.cost += e.cost_usd ?? 0;
    t.ms += e.duration_ms ?? 0;
  }
  return totals;
}

