// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
import { homedir } from 'node:os';
import { basename, join } from 'node:path';
import { exec, sha } from './util.mjs';

export async function git(cwd        , ...args          )                  {
  const res = await exec('git', args, { cwd });
  if (res.code !== 0) throw new Error(`git ${args.join(' ')} failed in ${cwd}: ${res.stderr.trim() || res.stdout.trim()}`);
  return res.stdout.trimEnd();
}

export async function repoRoot(cwd        )                  {
  return git(cwd, 'rev-parse', '--show-toplevel');
}

export const head = (cwd        ) => git(cwd, 'rev-parse', 'HEAD');

export async function currentBranch(cwd        )                  {
  return git(cwd, 'rev-parse', '--abbrev-ref', 'HEAD');
}

export function worktreePath(repo        , worktreesDir               , runId        , featureId        )         {
  const root = worktreesDir ?? join(homedir(), '.orchestra', 'worktrees');
  return join(root, `${basename(repo)}-${sha(repo).slice(0, 8)}`, runId, featureId);
}

export async function addWorktree(repo        , path        , branch        , base        )                {
  await git(repo, 'worktree', 'add', '-b', branch, path, base);
}

/** Stage everything (respecting .gitignore) so diffs include new files uniformly. */
async function stageAll(wt        )                {
  await git(wt, 'add', '-A');
}

/** Tree hash of the full working state — used to prove a read-only agent changed nothing. */
export async function snapshot(wt        )                  {
  await stageAll(wt);
  return git(wt, 'write-tree');
}

/** Restore the worktree to a previous snapshot (drops anything added since). */
export async function restore(wt        , tree        )                {
  await stageAll(wt);
  await git(wt, 'read-tree', '--reset', '-u', tree);
}

export async function changedFiles(wt        , base        )                    {
  await stageAll(wt);
  const out = await git(wt, 'diff', '--cached', '--name-only', base);
  return out ? out.split('\n') : [];
}

export async function diff(wt        , base        , maxChars = 200_000)                                           {
  await stageAll(wt);
  const stat = await git(wt, 'diff', '--cached', '--stat', base);
  let patch = await git(wt, 'diff', '--cached', base);
  if (patch.length > maxChars) patch = patch.slice(0, maxChars) + `\n…(diff truncated, ${patch.length - maxChars} more chars — inspect the worktree)`;
  return { stat, patch };
}

export async function commitAll(wt        , message        )                         {
  await stageAll(wt);
  const status = await git(wt, 'status', '--porcelain');
  if (!status) return null;
  // --no-verify: orchestra runs the project's checks itself before committing.
  await git(wt, 'commit', '-q', '--no-verify', '-m', message);
  return head(wt);
}
