// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
// JSON artifacts → human-readable markdown (Spec Kit–style files under specs/NNN-slug/).

const list = (items          ) => (items.length ? items.map((i) => `- ${i}`).join('\n') : '_None._');

export function renderDecomposition(d     )         {
  return [
    '# Feature decomposition',
    d.rationale,
    ...d.features.map(
      (f     ) =>
        `## ${f.id} — ${f.title} (\`${f.slug}\`)\n${f.summary}\n\n**Scope:** ${f.scope}\n\n**Depends on:** ${f.depends_on.join(', ') || 'nothing'}`,
    ),
  ].join('\n\n');
}

export function renderResearch(r     )         {
  return [
    '# Research',
    r.summary,
    '## Recommended approach',
    r.recommended_approach,
    '## Consensus',
    list(r.consensus),
    '## Disagreements',
    r.disagreements.length
      ? r.disagreements.map((x     ) => `### ${x.topic}\n- **Claude:** ${x.claude}\n- **Codex:** ${x.codex}\n- **Assessment:** ${x.assessment}`).join('\n\n')
      : '_None._',
    '## Key files',
    list(r.key_files.map((f     ) => `\`${f.path}\` — ${f.why}`)),
    '## Risks',
    list(r.risks),
    '## Open questions',
    list(r.open_questions),
  ].join('\n\n');
}

export function renderSpec(s     )         {
  return [
    `# Spec: ${s.title}`,
    s.summary,
    '## User stories',
    list(s.user_stories.map((u     ) => `**${u.id}** As a ${u.as_a}, I want ${u.i_want}, so that ${u.so_that}.`)),
    '## Functional requirements',
    list(s.functional_requirements.map((r     ) => `**${r.id}** ${r.text}`)),
    '## Non-functional requirements',
    list(s.non_functional_requirements.map((r     ) => `**${r.id}** ${r.text}`)),
    '## Acceptance criteria',
    list(s.acceptance_criteria.map((a     ) => `**${a.id}** Given ${a.given}, when ${a.when}, then ${a.then}.`)),
    '## Edge cases',
    list(s.edge_cases),
    '## Out of scope',
    list(s.out_of_scope),
    '## Assumptions',
    list(s.assumptions),
  ].join('\n\n');
}

export function renderPlan(p     , extra                                                            )         {
  const parts = [
    '# Implementation plan',
    p.summary,
    '## Architecture',
    p.architecture,
    '## Components',
    list(p.components.map((c     ) => `**${c.name}** — ${c.responsibility}${c.files.length ? ` (${c.files.map((f        ) => `\`${f}\``).join(', ')})` : ''}`)),
    '## Data model',
    p.data_model,
    '## Decisions',
    p.decisions.length
      ? p.decisions.map((d     ) => `### ${d.topic}\n**Choice:** ${d.choice}\n\n${d.rationale}${d.alternatives.length ? `\n\n_Alternatives:_ ${d.alternatives.join('; ')}` : ''}`).join('\n\n')
      : '_None._',
    '## File changes',
    list(p.file_changes.map((f     ) => `\`${f.path}\` (${f.change}) — ${f.description}`)),
    '## Testing strategy',
    p.testing_strategy,
    '## Risks',
    list(p.risks.map((r     ) => `${r.risk} → _${r.mitigation}_`)),
    '## Rollout',
    p.rollout,
  ];
  if (extra?.conflicts?.length) {
    parts.push(
      '## Claude vs Codex conflicts',
      extra.conflicts
        .map((c     ) => `### ${c.id} — ${c.topic} [${c.category}, ${c.status}]\n- **Claude:** ${c.claude_position}\n- **Codex:** ${c.codex_position}\n- **Resolution:** ${c.resolution ?? 'decided by user — see decisions.md'}`)
        .join('\n\n'),
    );
  }
  if (extra?.accepted?.length || extra?.rejected?.length) {
    parts.push(
      '## Challenge outcomes',
      list([
        ...(extra.accepted ?? []).map((a     ) => `✅ ${a.source} ${a.id}: ${a.change_made}`),
        ...(extra.rejected ?? []).map((r     ) => `❌ ${r.source} ${r.id}: ${r.reason}`),
      ]),
    );
  }
  return parts.join('\n\n');
}

export function renderTasks(t     , assignments                        )         {
  return [
    '# Tasks',
    ...t.tasks.map(
      (task     ) =>
        `## ${task.id} — ${task.title}\n_Implementer: ${assignments[task.id] ?? '?'} · depends on: ${task.depends_on.join(', ') || 'nothing'}_\n\n${task.description}\n\n**Files:** ${task.files_in_scope.map((f        ) => `\`${f}\``).join(', ') || '—'}\n\n**Acceptance:**\n${list(task.acceptance)}${task.test_command ? `\n\n**Test:** \`${task.test_command}\`` : ''}`,
    ),
  ].join('\n\n');
}

export function renderDecisions(entries                                                       )         {
  const out = ['# Decisions'];
  for (const e of entries) {
    out.push(`## ${e.phase}`);
    for (const a of e.answers) {
      const q = e.questions.find((x     ) => x.id === a.id);
      const recs = q
        ? [q.claude && `Claude → ${q.claude.recommendation ?? '—'}`, q.codex && `Codex → ${q.codex.recommendation ?? '—'}`].filter(Boolean).join(' · ')
        : '';
      out.push(`- **${a.id}** ${a.question}\n  - **Decision:** ${a.label}${recs ? `\n  - _${recs}_` : ''}`);
    }
  }
  return out.join('\n\n');
}

export function renderReport(r   
               
                                                                                                                                                   
                
              
 )         {
  return [
    `# Report: ${r.feature.id} — ${r.feature.title}`,
    `**Convergence:** ${r.converge.status} — ${r.converge.summary}`,
    '## Tasks',
    '| Task | Implementer | Reviewer | Rounds | Result |\n|---|---|---|---|---|\n' +
      r.tasks
        .map((t) => `| ${t.id} ${t.title} | ${t.implementer} | ${t.reviewer} | ${t.rounds} | ${t.accepted_with_issues ? '⚠️ accepted with issues' : '✅ approved'} ${t.sha ? `\`${t.sha.slice(0, 8)}\`` : ''} |`)
        .join('\n'),
    '## Acceptance criteria',
    list(r.converge.acceptance.map((a     ) => `${a.met ? '✅' : '❌'} **${a.id}** ${a.evidence}`)),
    '## Open findings',
    list(r.converge.findings.map((f     ) => `[${f.severity}] ${f.file ? `\`${f.file}\` ` : ''}${f.issue}`)),
    '## Final checks',
    r.checks ? list(r.checks.commands.map((c     ) => `${c.exit_code === 0 ? '✅' : '❌'} \`${c.cmd}\``)) : '_Not run._',
  ].join('\n\n');
}
