// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
import { readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { appendLine, exists, readJson, readText, slugify, writeJson, writeText } from './util.mjs';
                                         

                                                                                                     

                        
             
                  
               
                    
                                                           
                         
                      
                      
                     
                     
  

export const orchDir = (repo        ) => join(repo, '.orchestra');
export const runsDir = (repo        ) => join(orchDir(repo), 'runs');
export const runDir = (repo        , id        ) => join(runsDir(repo), id);

export function newRunId(request        , now = new Date())         {
  const p = (n        ) => String(n).padStart(2, '0');
  const stamp = `${now.getFullYear()}${p(now.getMonth() + 1)}${p(now.getDate())}-${p(now.getHours())}${p(now.getMinutes())}${p(now.getSeconds())}`;
  return `${stamp}-${slugify(request, 30)}`;
}

export function currentRunId(repo        )                {
  const id = readText(join(orchDir(repo), 'current')).trim();
  return id || null;
}

export function setCurrentRun(repo        , id        )       {
  writeText(join(orchDir(repo), 'current'), id + '\n');
}

export function listRuns(repo        )           {
  return exists(runsDir(repo)) ? readdirSync(runsDir(repo)).sort() : [];
}

export function loadState(dir        )           {
  return readJson          (join(dir, 'state.json'));
}

export function saveState(dir        , state          )       {
  state.updated_at = new Date().toISOString();
  writeJson(join(dir, 'state.json'), state);
}

export function logEvent(dir        , event                         )       {
  appendLine(join(dir, 'events.jsonl'), JSON.stringify({ ts: new Date().toISOString(), ...event }));
}

/** Single-writer lock per run so two `orch run`s never advance the same run concurrently. */
export function acquireLock(dir        )             {
  const p = join(dir, 'run.lock');
  if (exists(p)) {
    const pid = Number(readText(p).trim());
    let alive = false;
    try {
      process.kill(pid, 0);
      alive = true;
    } catch {}
    if (alive && pid !== process.pid) throw new Error(`Run is already being advanced by pid ${pid} (lock: ${p})`);
  }
  writeText(p, String(process.pid));
  return () => rmSync(p, { force: true });
}
