// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync, appendFileSync } from 'node:fs';
import { dirname } from 'node:path';

export const exists = (p        ) => existsSync(p);

export function readJson         (p        )    {
  return JSON.parse(readFileSync(p, 'utf8'))     ;
}

export function readText(p        , fallback = '')         {
  return existsSync(p) ? readFileSync(p, 'utf8') : fallback;
}

/** Atomic write: write to a temp file then rename, so a crash never leaves half a file. */
export function writeText(p        , content        )       {
  mkdirSync(dirname(p), { recursive: true });
  const tmp = `${p}.tmp-${process.pid}`;
  writeFileSync(tmp, content);
  renameSync(tmp, p);
}

export function writeJson(p        , data         )       {
  writeText(p, JSON.stringify(data, null, 2) + '\n');
}

export function appendLine(p        , line        )       {
  mkdirSync(dirname(p), { recursive: true });
  appendFileSync(p, line + '\n');
}

export const sha = (s        ) => createHash('sha256').update(s).digest('hex');

export function slugify(s        , max = 40)         {
  return (
    s
      .toLowerCase()
      .normalize('NFKD')
      .replace(/[^\w\s-]/g, '')
      .trim()
      .replace(/[\s_-]+/g, '-')
      .slice(0, max)
      .replace(/-+$/, '') || 'run'
  );
}

export function tail(s        , n = 4000)         {
  return s.length <= n ? s : `…(truncated ${s.length - n} chars)…\n` + s.slice(-n);
}

export function fmtMs(ms        )         {
  const s = Math.round(ms / 1000);
  return s < 60 ? `${s}s` : `${Math.floor(s / 60)}m${String(s % 60).padStart(2, '0')}s`;
}

                                                                                                                 

export function exec(
  cmd        ,
  args          ,
  opts                                                                               = { cwd: process.cwd() },
)                      {
  const started = Date.now();
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd: opts.cwd, env: opts.env ?? process.env, stdio: ['pipe', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    let timedOut = false;
    const timer = opts.timeoutMs
      ? setTimeout(() => {
          timedOut = true;
          child.kill('SIGTERM');
          setTimeout(() => child.kill('SIGKILL'), 5000).unref();
        }, opts.timeoutMs)
      : undefined;
    child.stdout.on('data', (d) => (stdout += d));
    child.stderr.on('data', (d) => (stderr += d));
    child.on('error', (err) => {
      clearTimeout(timer);
      reject(err);
    });
    child.on('close', (code) => {
      clearTimeout(timer);
      resolve({ code: code ?? -1, stdout, stderr, timedOut, durationMs: Date.now() - started });
    });
    child.stdin.end(opts.input ?? '');
  });
}

export function sh(command        , cwd        , timeoutMs         )                      {
  return exec('/bin/sh', ['-c', command], { cwd, timeoutMs });
}

export function topoSort                                                (items     )      {
  const byId = new Map(items.map((i) => [i.id, i]));
  const out      = [];
  const state = new Map                             ();
  const visit = (item   , trail          ) => {
    const s = state.get(item.id);
    if (s === 'done') return;
    if (s === 'visiting') throw new Error(`Dependency cycle: ${[...trail, item.id].join(' → ')}`);
    state.set(item.id, 'visiting');
    for (const dep of item.depends_on) {
      const d = byId.get(dep);
      if (!d) throw new Error(`${item.id} depends on unknown id "${dep}"`);
      visit(d, [...trail, item.id]);
    }
    state.set(item.id, 'done');
    out.push(item);
  };
  for (const i of items) visit(i, []);
  return out;
}
