// Generated by scripts/build.mjs from the TypeScript sources in src/. Do not edit.
import { join } from 'node:path';
import { exists, readJson } from './util.mjs';
                                              

                                                  

                                                               
                           
                
                 
                                                                                       
                                       
                   
  

export function resolveAgent(cfg             , role        )                                    {
  const r = cfg.roles?.[role] ?? {};
  return { model: r.model ?? cfg.model, effort: r.effort ?? cfg.effort };
}

                      
                                         
               
                                                                                       
                                  
                               
                                                                                                                              
                         
                            
           
                                                                                          
                       
                                                                                                        
                     
                                                                                   
                          
    
                                            
                          
                                                                                                
                                
                                                                                
                            
                               
  

export const DEFAULT_CONFIG         = {
  agents: {
    claude: { model: 'claude-opus-5-5', effort: 'high', roles: { scanner: { effort: 'medium' }, questioner: { effort: 'medium' } } },
    // Codex is the slower model on every parallel step; analysis roles run at medium so it stops gating them.
    codex: {
      model: 'gpt-6.1-sol',
      effort: 'high',
      roles: Object.fromEntries(['scanner', 'questioner', 'researcher', 'rebutter', 'challenger', 'reviewer'].map((r) => [r, { effort: 'medium' }])),
    },
  },
  depth: 'standard',
  synthesizer_fallback: 'claude',
  first_implementer: 'claude',
  parallel_tasks: 3,
  max_review_rounds: 3,
  review: { blocking: ['critical', 'high', 'medium'], polish: ['low'], polish_rounds: 1 },
  max_clarify_rounds: { quick: 1, standard: 2, deep: 3 },
  timeout_minutes: 45,
  escalate_categories: ['requirements', 'architecture', 'security', 'constitution', 'other'],
  checks: { setup: null, commands: [], timeout_minutes: 20 },
  protected_paths: ['.env', '.env.*', '**/.env', '**/.env.*', '**/*.pem', '**/*.key', '**/secrets/**', '.github/workflows/**'],
  worktrees_dir: null,
};

function merge   (base   , over     )    {
  if (!over || typeof over !== 'object' || Array.isArray(over)) return (over ?? base)     ;
  const out      = { ...base };
  for (const [k, v] of Object.entries(over)) {
    out[k] = v && typeof v === 'object' && !Array.isArray(v) ? merge((base       )?.[k] ?? {}, v) : v;
  }
  return out;
}

export function loadConfig(repo        )         {
  const p = join(repo, '.duet', 'config.json');
  return exists(p) ? merge(DEFAULT_CONFIG, readJson(p)) : DEFAULT_CONFIG;
}

/** Best-effort detection of install/test commands for `duet init`. */
export function detectChecks(repo        )                   {
  const checks                   = { setup: null, commands: [], timeout_minutes: 20 };
  const pkgPath = join(repo, 'package.json');
  if (!exists(pkgPath)) return checks;
  const pkg = readJson(pkgPath);
  const pm = exists(join(repo, 'pnpm-lock.yaml'))
    ? 'pnpm'
    : exists(join(repo, 'yarn.lock'))
      ? 'yarn'
      : exists(join(repo, 'bun.lockb')) || exists(join(repo, 'bun.lock'))
        ? 'bun'
        : 'npm';
  const hasDeps = ['dependencies', 'devDependencies', 'optionalDependencies'].some((k) => Object.keys(pkg[k] ?? {}).length);
  if (hasDeps) checks.setup = { pnpm: 'pnpm install --frozen-lockfile', yarn: 'yarn install --frozen-lockfile', bun: 'bun install', npm: exists(join(repo, 'package-lock.json')) ? 'npm ci' : 'npm install' }[pm] ;
  const run = pm === 'npm' ? 'npm run' : pm;
  for (const script of ['typecheck', 'lint', 'test']) {
    if (pkg.scripts?.[script]) checks.commands.push(script === 'test' && pm === 'npm' ? 'npm test' : `${run} ${script}`);
  }
  return checks;
}
